INSERT INTO monsters (slug, cr, size, type, name)
    VALUES ('hobgoblin', '1/2', 'Medium', 'humanoid', 'Hobgoblin'),
		('homunculus', '0', 'Tiny', 'construct', 'Homunculus'),
		('horakh', '9', 'Medium', 'monstrosity', 'Horakh'),
		('horned-devil', '11', 'Large', 'fiend', 'Horned Devil'),
		('horned-serpent', '12', 'Large', 'monstrosity', 'Horned Serpent'),
		('hound-of-the-night', '5', 'Large', 'monstrosity', 'Hound Of The Night'),
		('hound-of-tindalos', '8', 'Medium', 'aberration', 'Hound of Tindalos'),
		('hraesvelgr-the-corpse-swallower', '19', 'Huge', 'giant', 'Hraesvelgr The Corpse Swallower'),
		('hulking-whelp', '5', 'Small', 'fey', 'Hulking Whelp'),
		('hundun', '10', 'Large', 'celestial', 'Hundun'),
		('hunter-shark', '2', 'Large', 'beast', 'Hunter Shark'),
		('hydra', '8', 'Huge', 'monstrosity', 'Hydra'),
		('hyena', '0', 'Medium', 'beast', 'Hyena'),
		('iaaffrat', '15', 'Large', 'swarm of Tiny elementals', 'Ia''affrat'),
		('ice-devil', '14', 'Large', 'fiend', 'Ice Devil'),
		('ice-maiden', '6', 'Medium', 'fey', 'Ice Maiden'),
		('ice-mephit', '1/2', 'Small', 'elemental', 'Ice Mephit'),
		('ichneumon', '11', 'Large', 'monstrosity', 'Ichneumon'),
		('idolic-deity', '8', 'Small', 'construct', 'Idolic Deity'),
		('ijiraq', '7', 'Medium', 'fey', 'Ijiraq'),
		('imp', '1', 'Tiny', 'fiend', 'Imp'),
		('imy-ut-ushabti', '3', 'Medium', 'monstrosity', 'Imy-Ut Ushabti'),
		('incinis', '10', 'Large', 'elemental', 'Incinis'),
		('infernal-knight', '16', 'Medium', 'fiend', 'Infernal Knight'),
		('ink-devil', '2', 'Small', 'fiend', 'Ink Devil'),
		('ink-guardian', '4', 'Large', 'ooze', 'Ink Guardian'),
		('inkling', '1/4', 'Tiny', 'construct', 'Inkling'),
		('invisible-stalker', '6', 'Medium', 'elemental', 'Invisible Stalker'),
		('iron-golem', '16', 'Large', 'construct', 'Iron Golem'),
		('iron-sphere', '5', 'Small', 'construct', 'Iron Sphere'),
		('isonade', '14', 'Gargantuan', 'monstrosity', 'Isonade'),
		('jba-fofi-spider', '3', 'Large', 'beast', 'J''ba Fofi Spider'),
		('jaanavar-jal', '7', 'Huge', 'monstrosity', 'Jaanavar Jal'),
		('jackal', '0', 'Small', 'beast', 'Jackal'),
		('jaculus', '3', 'Small', 'dragon', 'Jaculus'),
		('jiangshi', '6', 'Medium', 'undead', 'Jiangshi'),
		('jinmenju', '9', 'Huge', 'plant', 'Jinmenju'),
		('jotun-giant', '22', 'Gargantuan', 'giant', 'Jotun Giant'),
		('junk-shaman', '2', 'Small', 'humanoid', 'Junk Shaman'),
		('kalke', '1/4', 'Small', 'fiend', 'Kalke'),
		('kallikantzaros', '2', 'Small', 'fey', 'Kallikantzaros'),
		('kapi', '1/2', 'Medium', 'humanoid', 'Kapi'),
		('kappa', '2', 'Small', 'fey', 'Kappa'),
		('karakura', '5', 'Medium', 'fiend', 'Karakura'),
		('keg-golem', '3', 'Medium', 'construct', 'Keg Golem'),
		('kikimora', '5', 'Medium', 'fey', 'Kikimora'),
		('killer-whale', '3', 'Huge', 'beast', 'Killer Whale'),
		('king-kobold', '6', 'Small', 'humanoid', 'King Kobold'),
		('kinnara', '3', 'Medium', 'celestial', 'Kinnara'),
		('kishi-demon', '8', 'Medium', 'fiend', 'Kishi Demon'),
		('kitsune', '2', 'Small', 'fey', 'Kitsune'),
		('knight', '3', 'Medium', 'humanoid', 'Knight'),
		('knight-of-the-road', '5', 'Medium', 'humanoid', 'Knight of the Road'),
		('kobold', '1/8', 'Small', 'humanoid', 'Kobold'),
		('kobold-alchemist', '2', 'Small', 'humanoid', 'Kobold Alchemist'),
		('kobold-chieftain', '4', 'Small', 'humanoid', 'Kobold Chieftain'),
		('kobold-trapsmith', '1', 'Small', 'humanoid', 'Kobold Trapsmith'),
		('kongamato', '5', 'Large', 'beast', 'Kongamato'),
		('koralk-harvester-devil', '11', 'Large', 'fiend', 'Koralk (Harvester Devil)'),
		('korrigan', '3', 'Small', 'fey', 'Korrigan'),
		('koschei', '17', 'Medium', 'fiend', 'Koschei'),
		('kot-bayun', '2', 'Medium', 'monstrosity', 'Kot Bayun'),
		('krake-spawn', '9', 'Huge', 'monstrosity', 'Krake Spawn'),
		('kraken', '23', 'Gargantuan', 'monstrosity', 'Kraken'),
		('kryt', '5', 'Medium', 'humanoid', 'Kryt'),
		('kuunganisha', '2', 'Small', 'fiend', 'Kuunganisha'),
		('kulmking', '9', 'Large', 'undead', 'Külmking'),
		('labyrinth-keeper', '5', 'Large', 'monstrosity', 'Labyrinth Keeper'),
		('lady-in-white', '2', 'Medium', 'undead', 'Lady in White'),
		('laestrigonian-giant', '4', 'Large', 'giant', 'Laestrigonian Giant'),
		('lake-troll', '7', 'Large', 'giant', 'Lake Troll'),
		('lamassu', '10', 'Large', 'celestial', 'Lamassu'),
		('lamia', '4', 'Large', 'monstrosity', 'Lamia'),
		('lantern-dragonette', '1/2', 'Tiny', 'dragon', 'Lantern Dragonette'),
		('lemure', '0', 'Medium', 'fiend', 'Lemure'),
		('lemurfolk', '1/4', 'Small', 'humanoid', 'Lemurfolk'),
		('lemurfolk-greyfur', '4', 'Small', 'humanoid', 'Lemurfolk Greyfur'),
		('leonino', '1/8', 'Tiny', 'beast', 'Leonino'),
		('leshy', '1', 'Medium', 'monstrosity', 'Leshy'),
		('lesser-scrag', '2', 'Medium', 'monstrosity', 'Lesser Scrag'),
		('library-automaton', '1/2', 'Small', 'construct', 'Library Automaton'),
		('lich', '21', 'Medium', 'undead', 'Lich'),
		('lich-hound', '4', 'Medium', 'undead', 'Lich Hound'),
		('light-cavalry', '1', 'Medium', 'humanoid', 'Light Cavalry'),
		('light-dragon-wyrmling', '2', 'Medium', 'dragon', 'Light Dragon Wyrmling'),
		('likho', '6', 'Medium', 'monstrosity', 'Likho'),
		('lindwurm', '5', 'Large', 'dragon', 'Lindwurm'),
		('lion', '1', 'Large', 'beast', 'Lion'),
		('liosalfar', '8', 'Large', 'elemental', 'Liosalfar'),
		('living-shade', '1/4', 'Medium', 'fey', 'Living Shade'),
		('living-star', '19', 'Huge', 'celestial', 'Living Star'),
		('living-wick', '1/4', 'Small', 'construct', 'Living Wick'),
		('lizard', '0', 'Tiny', 'beast', 'Lizard'),
		('lizardfolk', '1/2', 'Medium', 'humanoid', 'Lizardfolk'),
		('lord-of-the-hunt', '18', 'Medium', 'fey', 'Lord Of The Hunt'),
		('lord-zombie', '5', 'Medium', 'undead', 'Lord Zombie'),
		('lorelei', '5', 'Medium', 'fey', 'Lorelei'),
		('lost-minotaur', '8', 'Large', 'undead', 'Lost Minotaur'),
		('lotus-golem', '9', 'Large', 'construct', 'Lotus Golem'),
		('lou-carcolh', '2', 'Medium', 'monstrosity', 'Lou Carcolh'),
		('loxoda', '6', 'Huge', 'monstrosity', 'Loxoda'),
		('lunar-devil', '8', 'Large', 'fiend', 'Lunar Devil'),
		('lystrosaurus', '2', 'Medium', 'beast', 'Lystrosaurus'),
		('mage', '6', 'Medium', 'humanoid', 'Mage'),
		('magma-mephit', '1/2', 'Small', 'elemental', 'Magma Mephit'),
		('magmin', '1/2', 'Small', 'elemental', 'Magmin'),
		('mahoru', '3', 'Large', 'monstrosity', 'Mahoru'),
		('malakbel', '9', 'Medium', 'fiend', 'Malakbel'),
		('mallqui', '8', 'Medium', 'undead', 'Mallqui'),
		('malphas-storm-crow', '6', 'Medium', 'fey', 'Malphas (Storm Crow)'),
		('mammon', '25', 'Huge', 'fiend', 'Mammon'),
		('mammoth', '6', 'Huge', 'beast', 'Mammoth'),
		('mamura', '6', 'Small', 'aberration', 'Mamura'),
		('manabane-scarab-swarm', '4', 'Medium', 'Swarm of Tiny beasts', 'Manabane Scarab Swarm'),
		('manastorm-golem', '8', 'Medium', 'construct', 'Manastorm Golem'),
		('mandrake', '1/2', 'Tiny', 'plant', 'Mandrake'),
		('mandriano', '5', 'Large', 'plant', 'Mandriano'),
		('manticore', '3', 'Large', 'monstrosity', 'Manticore'),
		('map-mimic', '1/4', 'Tiny', 'aberration', 'Map Mimic'),
		('marilith', '16', 'Large', 'fiend', 'Marilith'),
		('mask-wight', '13', 'Medium', 'undead', 'Mask Wight'),
		('mastiff', '1/8', 'Medium', 'beast', 'Mastiff'),
		('matriarch-serpentine-lamia', '5', 'Large', 'monstrosity', 'Matriarch Serpentine Lamia'),
		('mavka', '12', 'Medium', 'undead', 'Mavka'),
		('mbielu', '3', 'Huge', 'beast', 'Mbielu'),
		('mechuiti-demon-lord-of-apes', '27', 'Gargantuan', 'fiend', 'Mechuiti, Demon Lord Of Apes'),
		('medusa', '6', 'Medium', 'monstrosity', 'Medusa'),
		('megapede', '3', 'Large', 'monstrosity', 'Megapede'),
		('merfolk', '1/8', 'Medium', 'humanoid', 'Merfolk'),
		('merrow', '2', 'Large', 'monstrosity', 'Merrow'),
		('mi-go', '5', 'Medium', 'plant', 'Mi-Go'),
		('millitaur', '3', 'Large', 'monstrosity', 'Millitaur'),
		('mimic', '2', 'Medium', 'monstrosity', 'Mimic'),
		('mindrot-thrall', '3', 'Medium', 'plant', 'Mindrot Thrall'),
		('minotaur', '3', 'Large', 'monstrosity', 'Minotaur'),
		('minotaur-skeleton', '2', 'Large', 'undead', 'Minotaur Skeleton'),
		('mirager', '3', 'Medium', 'fey', 'Mirager'),
		('miremal', '1/2', 'Small', 'fey', 'Miremal'),
		('mirror-hag', '6', 'Medium', 'fey', 'Mirror Hag'),
		('mngwa', '4', 'Medium', 'aberration', 'Mngwa'),
		('mold-zombie', '3', 'Medium', 'undead', 'Mold Zombie'),
		('monarch-skeleton', '9', 'Medium', 'undead', 'Monarch Skeleton'),
		('monkey-king', '21', 'Medium', 'celestial', 'Monkey King'),
		('monolith-champion', '8', 'Large', 'construct', 'Monolith Champion'),
		('monolith-footman', '3', 'Large', 'construct', 'Monolith Footman'),
		('moon-drake', '5', 'Medium', 'dragon', 'Moon Drake'),
		('moon-nymph', '8', 'Medium', 'aberration', 'Moon Nymph'),
		('moonchild-naga', '6', 'Large', 'monstrosity', 'Moonchild Naga'),
		('moonlit-king', '17', 'Medium', 'fey', 'Moonlit King'),
		('mordant-snare', '15', 'Gargantuan', 'aberration', 'Mordant Snare'),
		('morko', '1/4', 'Small', 'fey', 'Morko'),
		('morphoi', '1/2', 'Medium', 'plant', 'Morphoi'),
		('moss-lurker', '1', 'Small', 'humanoid', 'Moss Lurker'),
		('mountain-giant', '21', 'Gargantuan', 'giant', 'Mountain Giant'),
		('mud-golem', '1', 'Small', 'construct', 'Mud Golem'),
		('mule', '1/8', 'Medium', 'beast', 'Mule'),
		('mummy', '3', 'Medium', 'undead', 'Mummy'),
		('mummy-lord', '15', 'Medium', 'undead', 'Mummy Lord'),
		('myling', '2', 'Small', 'undead', 'Myling'),
		('mytholabe', '9', 'Large', 'construct', 'Mytholabe'),
		('nachzehrer', '8', 'Medium', 'undead', 'Nachzehrer'),
		('naina', '11', 'Large', 'dragon', 'Naina'),
		('nalfeshnee', '13', 'Large', 'fiend', 'Nalfeshnee'),
		('nalusa-falaya', '1/2', 'Medium', 'aberration', 'Nalusa Falaya'),
		('necrophage-ghast', '4', 'Medium', 'undead', 'Necrophage Ghast'),
		('necrotic-tick', '1/4', 'Tiny', 'beast', 'Necrotic Tick'),
		('neophron', '8', 'Medium', 'fiend', 'Neophron'),
		('ngobou', '5', 'Large', 'beast', 'Ngobou'),
		('nian', '4', 'Large', 'monstrosity', 'Nian'),
		('nichny', '6', 'Medium', 'fey', 'Nichny'),
		('night-hag', '5', 'Medium', 'fiend', 'Night Hag'),
		('night-scorpion', '3', 'Large', 'beast', 'Night Scorpion'),
		('nightgarm', '6', 'Large', 'monstrosity', 'Nightgarm'),
		('nightgaunt', '10', 'Large', 'aberration', 'Nightgaunt'),
		('nightmare', '3', 'Large', 'fiend', 'Nightmare'),
		('nihilethic-zombie', '1', 'Medium', 'undead', 'Nihilethic Zombie'),
		('ningyo', '7', 'Small', 'aberration', 'Ningyo'),
		('nkosi', '1/2', 'Medium', 'humanoid (shapechanger', 'Nkosi'),
		('nkosi-pridelord', '4', 'Medium', 'humanoid (shapechanger', 'Nkosi Pridelord'),
		('nkosi-war-ostrich', '1/2', 'Large', 'beast', 'Nkosi War Ostrich'),
		('noble', '1/8', 'Medium', 'humanoid', 'Noble'),
		('noctiny', '2', 'Medium', 'humanoid', 'Noctiny'),
		('nodosaurus', '1', 'Large', 'beast', 'Nodosaurus'),
		('ochre-jelly', '2', 'Large', 'ooze', 'Ochre Jelly'),
		('octopus', '0', 'Small', 'beast', 'Octopus'),
		('oculo-swarm', '4', 'Large', 'swarm of Tiny aberrations', 'Oculo Swarm'),
		('ogre', '2', 'Large', 'giant', 'Ogre'),
		('ogre-chieftain-corrupted', '6', 'Large', 'giant', 'Ogre Chieftain, Corrupted'),
		('ogre-zombie', '2', 'Large', 'undead', 'Ogre Zombie'),
		('oliphaunt', '8', 'Gargantuan', 'beast', 'Oliphaunt'),
		('one-headed-clockwork-dragon', '8', 'Large', 'construct', 'One-Headed Clockwork Dragon'),
		('oni', '7', 'Large', 'giant', 'Oni'),
		('oozasis', '9', 'Gargantuan', 'ooze', 'Oozasis'),
		('ophanim', '16', 'Large', 'celestial', 'Ophanim'),
		('orc', '1/2', 'Medium', 'humanoid', 'Orc'),
		('orobas-devil', '14', 'Large', 'fiend', 'Orobas Devil'),
		('orthrus', '3', 'Medium', 'monstrosity', 'Orthrus'),
		('ostinato', '4', 'Medium', 'aberration', 'Ostinato'),
		('oth', '5', 'Large', 'aberration', 'Oth'),
		('otyugh', '5', 'Large', 'aberration', 'Otyugh'),
		('ouroban', '11', 'Medium', 'humanoid', 'Ouroban'),
		('ouroboros', '6', 'Huge', 'dragon', 'Ouroboros'),
		('owl', '0', 'Tiny', 'beast', 'Owl'),
		('owl-harpy', '5', 'Medium', 'monstrosity', 'Owl Harpy'),
		('owlbear', '3', 'Large', 'monstrosity', 'Owlbear'),
		('pact-drake', '1', 'Small', 'dragon', 'Pact Drake'),
		('pact-lich', '15', 'Medium', 'undead', 'Pact Lich'),
		('panther', '1/4', 'Medium', 'beast', 'Panther'),
		('paper-drake', '2', 'Small', 'dragon', 'Paper Drake'),
		('paper-golem', '1/4', 'Tiny', 'construct', 'Paper Golem'),
		('paper-golem-swarm', '3', 'Medium', 'constructs', 'Paper Golem Swarm'),
		('pattern-dancer', '2', 'Medium', 'humanoid', 'Pattern Dancer'),
		('pech', '2', 'Small', 'elemental', 'Pech'),
		('pech-lithlord', '7', 'Small', 'elemental', 'Pech Lithlord'),
		('pech-stonemaster', '4', 'Small', 'elemental', 'Pech Stonemaster'),
		('pegasus', '2', 'Large', 'celestial', 'Pegasus'),
		('peluda-drake', '3', 'Large', 'dragon', 'Peluda Drake'),
		('phantom', '1', 'Medium', 'undead', 'Phantom'),
		('phase-spider', '3', 'Large', 'monstrosity', 'Phase Spider'),
		('philosophers-ghost', '4', 'Medium', 'ooze', 'Philosopher''s Ghost'),
		('piasa', '6', 'Large', 'dragon', 'Piasa'),
		('pillar-of-the-lost-magocracy', '4', 'Huge', 'construct', 'Pillar of the Lost Magocracy'),
		('pishacha', '3', 'Medium', 'fiend', 'Pishacha'),
		('pit-fiend', '20', 'Large', 'fiend', 'Pit Fiend'),
		('pixiu', '6', 'Large', 'monstrosity', 'Pixiu'),
		('planetar', '16', 'Large', 'celestial', 'Planetar'),
		('plaresh', '3', 'Medium', 'fiends', 'Plaresh'),
		('plesiosaurus', '2', 'Large', 'beast', 'Plesiosaurus'),
		('poisonous-snake', '1/8', 'Tiny', 'beast', 'Poisonous Snake'),
		('polar-bear', '2', 'Large', 'beast', 'Polar Bear'),
		('pombero', '3', 'Medium', 'fey', 'Pombero'),
		('pony', '1/8', 'Medium', 'beast', 'Pony'),
		('possessed-pillar', '7', 'Large', 'construct', 'Possessed Pillar'),
		('preta', '3', 'Medium', 'undead', 'Preta'),
		('priest', '2', 'Medium', 'humanoid', 'Priest'),
		('prismatic-beetle-swarm', '3', 'Medium', 'swarm of Tiny beasts', 'Prismatic Beetle Swarm'),
		('pseudodragon', '1/4', 'Tiny', 'dragon', 'Pseudodragon'),
		('psoglav-demon', '7', 'Large', 'fiend', 'Psoglav Demon'),
		('purple-slime', '3', 'Large', 'ooze', 'Purple Slime'),
		('purple-worm', '15', 'Gargantuan', 'monstrosity', 'Purple Worm'),
		('putrid-haunt', '2', 'Medium', 'undead', 'Putrid Haunt'),
		('qorgeth-demon-lord-of-the-devouring-worm', '23', 'Gargantuan', 'fiend', 'Qorgeth, Demon Lord Of The Devouring Worm'),
		('quasit', '1', 'Tiny', 'fiend', 'Quasit'),
		('queen-of-night-and-magic', '21', 'Medium', 'fey', 'Queen Of Night And Magic'),
		('queen-of-witches', '17', 'Large', 'fey', 'Queen Of Witches'),
		('quickstep', '5', 'Small', 'fey', 'Quickstep'),
		('quiet-soul', '6', 'Medium', 'undead', 'Quiet Soul'),
		('quipper', '0', 'Tiny', 'beast', 'Quipper'),
		('qwyllion', '8', 'Medium', 'aberration', 'Qwyllion'),
		('rageipede', '2', 'Small', 'beast', 'Rageipede'),
		('rakshasa', '13', 'Medium', 'fiend', 'Rakshasa'),
		('ramag', '1/4', 'Medium', 'humanoid', 'Ramag'),
		('ramag-portal-master', '5', 'Medium', 'humanoid', 'Ramag Portal Master'),
		('rat', '0', 'Tiny', 'beast', 'Rat'),
		('rat-king', '5', 'Medium', 'monstrosity', 'Rat King'),
		('ratatosk', '4', 'Tiny', 'celestial', 'Ratatosk'),
		('ratatosk-warlord', '5', 'Small', 'celestial', 'Ratatosk Warlord'),
		('ratfolk', '1/4', 'Small', 'humanoid', 'Ratfolk'),
		('ratfolk-mercenary', '2', 'Small', 'humanoid', 'Ratfolk Mercenary'),
		('ratfolk-rogue', '1', 'Small', 'humanoid', 'Ratfolk Rogue'),
		('ratfolk-warlock', '1', 'Small', 'humanoid', 'Ratfolk Warlock'),
		('rattok', '4', 'Small', 'fiend', 'Rattok'),
		('raven', '0', 'Tiny', 'beast', 'Raven'),
		('ravenala', '5', 'Large', 'plant', 'Ravenala'),
		('ravenfolk-doom-croaker', '5', 'Medium', 'humanoid', 'Ravenfolk Doom Croaker'),
		('ravenfolk-scout', '1/2', 'Medium', 'humanoid', 'Ravenfolk Scout'),
		('ravenfolk-warrior', '3', 'Medium', 'humanoid', 'Ravenfolk Warrior'),
		('razorleaf', '5', 'Medium', 'plant', 'Razorleaf'),
		('red-dragon-wyrmling', '4', 'Medium', 'dragon', 'Red Dragon Wyrmling'),
		('red-hag', '7', 'Medium', 'fey', 'Red Hag'),
		('red-banded-line-spider', '1/4', 'Tiny', 'beast', 'Red-Banded Line Spider'),
		('redcap', '6', 'Medium', 'fey', 'Redcap'),
		('reef-shark', '1/2', 'Medium', 'beast', 'Reef Shark'),
		('remorhaz', '11', 'Huge', 'monstrosity', 'Remorhaz'),
		('rhinoceros', '2', 'Large', 'beast', 'Rhinoceros'),
		('riding-horse', '1/4', 'Large', 'beast', 'Riding Horse'),
		('rift-swine', '5', 'Large', 'aberration', 'Rift Swine'),
		('rime-worm-grub', '1', 'Medium', 'elemental', 'Rime Worm Grub'),
		('rimewing', '1/4', 'Small', 'beast', 'Rimewing'),
		('ring-servant', '8', 'Large', 'construct', 'Ring Servant'),
		('risen-reaver', '7', 'Large', 'undead', 'Risen Reaver'),
		('river-king', '16', 'Medium', 'fey', 'River King'),
		('roachling-lord', '2', 'Small', 'humanoid', 'Roachling Lord'),
		('roachling-scout', '2', 'Small', 'humanoid', 'Roachling Scout'),
		('roachling-skirmisher', '1/4', 'Small', 'humanoid', 'Roachling Skirmisher'),
		('roc', '11', 'Gargantuan', 'monstrosity', 'Roc'),
		('roggenwolf', '2', 'Medium', 'monstrosity', 'Roggenwolf'),
		('roper', '5', 'Large', 'monstrosity', 'Roper'),
		('rotting-wind', '6', 'Large', 'undead', 'Rotting Wind'),
		('rubezahl', '10', 'Medium', 'fiend', 'Rubezahl'),
		('ruby-ooze', '6', 'Medium', 'ooze', 'Ruby Ooze'),
		('rug-of-smothering', '2', 'Large', 'construct', 'Rug of Smothering'),
		('rum-gremlin', '1/2', 'Tiny', 'fey', 'Rum Gremlin'),
		('rusalka', '6', 'Medium', 'undead', 'Rusalka'),
		('rust-drake', '8', 'Medium', 'dragon', 'Rust Drake'),
		('rust-monster', '1/2', 'Medium', 'monstrosity', 'Rust Monster'),
		('saber-toothed-tiger', '2', 'Large', 'beast', 'Saber-Toothed Tiger'),
		('sahuagin', '1/2', 'Medium', 'humanoid', 'Sahuagin'),
		('salamander', '5', 'Large', 'elemental', 'Salamander'),
		('salt-devil', '6', 'Medium', 'fiend', 'Salt Devil'),
		('salt-golem', '10', 'Large', 'construct', 'Salt Golem'),
		('sammael', '7', 'Medium', 'celestial', 'Sammael'),
		('sand-hag', '5', 'Medium', 'monstrosity', 'Sand Hag'),
		('sand-silhouette', '6', 'Medium', 'undead', 'Sand Silhouette'),
		('sand-spider', '7', 'Large', 'beast', 'Sand Spider'),
		('sandman', '5', 'Medium', 'celestial', 'Sandman'),
		('sandwyrm', '6', 'Large', 'dragon', 'Sandwyrm'),
		('sap-demon', '4', 'Small', 'ooze', 'Sap Demon'),
		('sarcophagus-slime', '5', 'Medium', 'undead', 'Sarcophagus Slime'),
		('sathaq-worm', '10', 'Huge', 'elemental', 'Sathaq Worm'),
		('satyr', '1/2', 'Medium', 'fey', 'Satyr'),
		('savager', '8', 'Large', 'beast', 'Savager'),
		('scheznyki', '6', 'Small', 'fey', 'Scheznyki'),
		('scitalis', '2', 'Large', 'monstrosity', 'Scitalis'),
		('scorpion', '0', 'Tiny', 'beast', 'Scorpion'),
		('scorpion-cultist', '1/2', 'Medium', 'humanoid (any race)', 'Scorpion Cultist'),
		('scout', '1/2', 'Medium', 'humanoid', 'Scout'),
		('sea-dragon-wyrmling', '2', 'Medium', 'dragon', 'Sea Dragon Wyrmling'),
		('sea-hag', '2', 'Medium', 'fey', 'Sea Hag'),
		('sea-horse', '0', 'Tiny', 'beast', 'Sea Horse'),
		('selang', '4', 'Medium', 'fey', 'Selang'),
		('sentinel-in-darkness', '7', 'Large', 'construct', 'Sentinel in Darkness'),
		('serpentfolk-of-yig', '1', 'Medium', 'humanoid', 'Serpentfolk of Yig'),
		('serpentine-lamia', '1', 'Medium', 'monstrosity', 'Serpentine Lamia'),
		('serpopard', '4', 'Large', 'beast', 'Serpopard'),
		('servant-of-yig', '4', 'Medium', 'aberration', 'Servant of Yig'),
		('servant-of-the-vine', '6', 'Medium', 'humanoid', 'Servant of the Vine'),
		('shabti', '8', 'Medium', 'construct', 'Shabti'),
		('shadhavar', '2', 'Large', 'monstrosity', 'Shadhavar'),
		('shadow', '1/2', 'Medium', 'undead', 'Shadow'),
		('shadow-beast', '7', 'Medium', 'fey', 'Shadow Beast'),
		('shadow-blight', '1', 'Small', 'plant', 'Shadow Blight'),
		('shadow-fey', '1/4', 'Medium', 'humanoid', 'Shadow Fey'),
		('shadow-fey-ambassador', '9', 'Medium', 'humanoid', 'Shadow Fey Ambassador'),
		('shadow-fey-duelist', '6', 'Medium', 'humanoid', 'Shadow Fey Duelist'),
		('shadow-fey-enchantress', '7', 'Medium', 'humanoid (shadow fey)', 'Shadow Fey Enchantress'),
		('shadow-fey-forest-hunter', '5', 'Medium', 'humanoid', 'Shadow Fey Forest Hunter'),
		('shadow-fey-guardian', '4', 'Large', 'humanoid', 'Shadow Fey Guardian'),
		('shadow-fey-poisoner', '11', 'Medium', 'humanoid', 'Shadow Fey Poisoner'),
		('shadow-goblin', '1/2', 'Small', 'humanoid', 'Shadow Goblin'),
		('shadow-ooze', '3', 'Medium', 'ooze', 'Shadow Ooze'),
		('shadow-river-lord', '9', 'Medium', 'undead', 'Shadow River Lord'),
		('shadow-skeleton', '2', 'Medium', 'undead', 'Shadow Skeleton'),
		('shambling-mound', '5', 'Large', 'plant', 'Shambling Mound'),
		('shantak', '5', 'Large', 'monstrosity', 'Shantak'),
		('shard-swarm', '1/2', 'Medium', 'constructs', 'Shard Swarm'),
		('sharkjaw-skeleton', '1', 'Large', 'undead', 'Sharkjaw Skeleton'),
		('shellycoat', '2', 'Medium', 'fey', 'Shellycoat'),
		('shield-guardian', '7', 'Large', 'construct', 'Shield Guardian'),
		('shockwing', '1', 'Small', 'beast', 'Shockwing'),
		('shoggoth', '19', 'Huge', 'aberration', 'Shoggoth'),
		('shoreline-scrapper', '4', 'Large', 'beast', 'Shoreline Scrapper'),
		('shrieker', '0', 'Medium', 'plant', 'Shrieker'),
		('shroud', '1/8', 'Medium', 'undead', 'Shroud'),
		('sigilian', '2', 'Medium', 'construct', 'Sigilian'),
		('silver-dragon-wyrmling', '2', 'Medium', 'dragon', 'Silver Dragon Wyrmling'),
		('simhamukha', '8', 'Huge', 'celestial', 'Simhamukha'),
		('simurg', '5', 'Gargantuan', 'celestial', 'Simurg'),
		('skein-witch', '12', 'Medium', 'celestial', 'Skein Witch'),
		('skeleton', '1/4', 'Medium', 'undead', 'Skeleton'),
		('skin-bat', '1/2', 'Small', 'undead', 'Skin Bat'),
		('skitterhaunt', '4', 'Large', 'ooze', 'Skitterhaunt'),
		('skull-drake', '3', 'Medium', 'dragon', 'Skull Drake'),
		('skull-lantern', '1/4', 'Tiny', 'undead', 'Skull Lantern'),
		('sleipnir', '5', 'Large', 'monstrosity', 'Sleipnir'),
		('slow-storm', '15', 'Huge', 'elemental', 'Slow Storm'),
		('sluagh-swarm', '3', 'Medium', 'swarm of Tiny fey', 'Sluagh Swarm'),
		('smaragdine-golem', '14', 'Large', 'construct', 'Smaragdine Golem'),
		('snow-cat', '1/4', 'Medium', 'beast', 'Snow Cat'),
		('snow-hag', '3', 'Medium', 'fey', 'Snow Hag'),
		('snow-queen', '16', 'Medium', 'fey', 'Snow Queen'),
		('solar', '21', 'Large', 'celestial', 'Solar'),
		('son-of-fenris', '12', 'Huge', 'monstrosity', 'Son Of Fenris'),
		('song-angel', '6', 'Large', 'celestial', 'Song Angel'),
		('sootwing', '1/4', 'Small', 'beast', 'Sootwing'),
		('sooze', '1/2', 'Medium', 'aberration', 'Sooze'),
		('soul-eater', '7', 'Medium', 'fiend', 'Soul Eater'),
		('spark', '7', 'Tiny', 'elemental', 'Spark'),
		('spawn-of-akyishigal', '5', 'Medium', 'fiend', 'Spawn Of Akyishigal'),
		('spawn-of-arbeyach', '5', 'Medium', 'fiend', 'Spawn Of Arbeyach'),
		('spawn-of-chernobog', '4', 'Large', 'fiend', 'Spawn of Chernobog'),
		('speaker-to-the-darkness', '5', 'Small', 'humanoid', 'Speaker to the Darkness'),
		('specter', '1', 'Medium', 'undead', 'Specter'),
		('spectral-guardian', '6', 'Medium', 'undead', 'Spectral Guardian'),
		('spider', '0', 'Tiny', 'beast', 'Spider'),
		('spider-drake', '9', 'Large', 'dragon', 'Spider Drake'),
		('spider-of-leng', '7', 'Large', 'aberration', 'Spider Of Leng'),
		('spider-thief', '2', 'Small', 'construct', 'Spider Thief'),
		('spinosaurus', '13', 'Gargantuan', 'beast', 'Spinosaurus'),
		('spire-walker', '3', 'Tiny', 'fey', 'Spire Walker'),
		('spirit-lamp', '7', 'Medium', 'undead', 'Spirit Lamp'),
		('spirit-naga', '8', 'Large', 'monstrosity', 'Spirit Naga'),
		('spree', '5', 'Small', 'fiend', 'Spree'),
		('sprite', '1/4', 'Tiny', 'fey', 'Sprite'),
		('spy', '1', 'Medium', 'humanoid', 'Spy'),
		('star-drake', '15', 'Large', 'dragon', 'Star Drake'),
		('star-spawn-of-cthulhu', '15', 'Large', 'fiend', 'Star Spawn Of Cthulhu'),
		('steam-golem', '13', 'Large', 'construct', 'Steam Golem'),
		('steam-mephit', '1/4', 'Small', 'elemental', 'Steam Mephit'),
		('stirge', '1/8', 'Tiny', 'beast', 'Stirge'),
		('stone-giant', '7', 'Huge', 'giant', 'Stone Giant'),
		('stone-golem', '10', 'Large', 'construct', 'Stone Golem'),
		('storm-giant', '13', 'Huge', 'giant', 'Storm Giant'),
		('storm-lord', '13', 'Huge', 'elemental', 'Storm Lord'),
		('storm-spirit', '1/2', 'Medium', 'elemental', 'Storm Spirit'),
		('stryx', '1/8', 'Tiny', 'monstrosity', 'Stryx'),
		('stuhac', '13', 'Medium', 'fiend', 'Stuhac'),
		('stygian-fat-tailed-scorpion', '3', 'Tiny', 'beast', 'Stygian Fat-Tailed Scorpion'),
		('subek', '5', 'Large', 'humanoid', 'Subek'),
		('succubusincubus', '4', 'Medium', 'fiend', 'Succubus/Incubus'),
		('sunset-raptor', '1', 'Medium', 'monstrosity', 'Sunset Raptor'),
		('suppurating-ooze', '1', 'Medium', 'ooze', 'Suppurating Ooze'),
		('suturefly', '1/4', 'Tiny', 'beast', 'Suturefly'),
		('swamp-adder', '1/4', 'Small', 'beast', 'Swamp Adder'),
		('swarm-of-bats', '1/4', 'Medium', 'swarm of Tiny beasts', 'Swarm of Bats'),
		('swarm-of-beetles', '1/2', 'Medium', 'swarm of Tiny beasts', 'Swarm of Beetles'),
		('swarm-of-centipedes', '1/2', 'Medium', 'swarm of Tiny beasts', 'Swarm of Centipedes'),
		('swarm-of-insects', '1/2', 'Medium', 'swarm of Tiny beasts', 'Swarm of Insects'),
		('swarm-of-poisonous-snakes', '2', 'Medium', 'swarm of Tiny beasts', 'Swarm of Poisonous Snakes'),
		('swarm-of-quippers', '1', 'Medium', 'swarm of Tiny beasts', 'Swarm of Quippers'),
		('swarm-of-rats', '1/4', 'Medium', 'swarm of Tiny beasts', 'Swarm of Rats'),
		('swarm-of-ravens', '1/4', 'Medium', 'swarm of Tiny beasts', 'Swarm of Ravens'),
		('swarm-of-spiders', '1/2', 'Medium', 'swarm of Tiny beasts', 'Swarm of Spiders'),
		('swarm-of-wasps', '1/2', 'Medium', 'swarm of Tiny beasts', 'Swarm of Wasps'),
		('swolbold', '3', 'Medium', 'humanoid', 'Swolbold'),
		('tar-ghoul', '4', 'Medium', 'undead', 'Tar Ghoul'),
		('tarrasque', '30', 'Gargantuan', 'monstrosity', 'Tarrasque'),
		('temple-dog', '5', 'Medium', 'celestial', 'Temple Dog'),
		('terror-bird', '2', 'Large', 'beast', 'Terror Bird'),
		('the-barbed', '1', 'Small', 'humanoid', 'The Barbed'),
		('thorned-sulfurlord', '11', 'Huge', 'fiend', 'Thorned Sulfurlord'),
		('thread-bound-constrictor-snake', '3', 'Huge', 'construct', 'Thread-Bound Constrictor Snake'),
		('three-headed-clockwork-dragon', '14', 'Huge', 'construct', 'Three-Headed Clockwork Dragon'),
		('three-headed-cobra', '5', 'Large', 'monstrosity', 'Three-Headed Cobra'),
		('thuellai', '10', 'Huge', 'elemental', 'Thuellai'),
		('thug', '1/2', 'Medium', 'humanoid', 'Thug'),
		('thursir-giant', '3', 'Large', 'giant', 'Thursir Giant'),
		('tiger', '1', 'Large', 'beast', 'Tiger'),
		('titanoboa', '12', 'Gargantuan', 'beast', 'Titanoboa'),
		('tophet', '8', 'Huge', 'construct', 'Tophet'),
		('tosculi-drone', '1/2', 'Small', 'monstrosity', 'Tosculi Drone'),
		('tosculi-elite-bow-raider', '5', 'Medium', 'humanoid', 'Tosculi Elite Bow Raider'),
		('tosculi-hive-queen', '12', 'Large', 'monstrosity', 'Tosculi Hive-Queen'),
		('tosculi-jeweled-drone', '4', 'Small', 'humanoid', 'Tosculi Jeweled Drone'),
		('tosculi-warrior', '2', 'Small', 'monstrosity', 'Tosculi Warrior'),
		('totivillus-scribe-of-hell', '24', 'Medium', 'fiend', 'Totivillus, Scribe Of Hell'),
		('treacle', '1/4', 'Tiny', 'ooze', 'Treacle'),
		('treant', '9', 'Huge', 'plant', 'Treant'),
		('tribal-warrior', '1/8', 'Medium', 'humanoid', 'Tribal Warrior'),
		('triceratops', '5', 'Huge', 'beast', 'Triceratops'),
		('troll', '5', 'Large', 'giant', 'Troll'),
		('trollkin-reaver', '4', 'Medium', 'humanoid', 'Trollkin Reaver'),
		('trollkin-shaman', '4', 'Medium', 'humanoid', 'Trollkin Shaman'),
		('trollking-grunt', '2', 'Medium', 'humanoid', 'Trollking Grunt'),
		('tulpa', '4', 'Medium', 'undead', 'Tulpa'),
		('tusked-crimson-ogre', '5', 'Large', 'giant', 'Tusked Crimson Ogre'),
		('tusked-skyfish', '4', 'Large', 'aberration', 'Tusked Skyfish'),
		('tveirherjar', '7', 'Medium', 'undead', 'Tveirherjar'),
		('two-headed-eagle', '7', 'Huge', 'monstrosity', 'Two-Headed Eagle'),
		('tyrannosaurus-rex', '8', 'Huge', 'beast', 'Tyrannosaurus Rex'),
		('umbral-vampire', '7', 'Medium', 'fiend', 'Umbral Vampire'),
		('undead-phoenix', '12', 'Huge', 'undead', 'Undead Phoenix'),
		('unhatched', '4', 'Small', 'undead', 'Unhatched'),
		('unicorn', '5', 'Large', 'celestial', 'Unicorn'),
		('uraeus', '2', 'Tiny', 'celestial', 'Uraeus'),
		('urochar-strangling-watcher', '17', 'Huge', 'aberration', 'Urochar (Strangling Watcher)'),
		('ursa-polaris', '7', 'Large', 'monstrosity', 'Ursa Polaris'),
		('ushabti', '9', 'Large', 'construct', 'Ushabti'),
		('vaettir', '4', 'Medium', 'undead', 'Vaettir'),
		('valkyrie', '11', 'Medium', 'celestial', 'Valkyrie'),
		('vampire', '13', 'Medium', 'undead', 'Vampire'),
		('vampire-patrician', '10', 'Medium', 'undead', 'Vampire Patrician'),
		('vampire-priestess', '8', 'Medium', 'undead', 'Vampire Priestess'),
		('vampire-spawn', '5', 'Medium', 'undead', 'Vampire Spawn'),
		('vampire-warlock-variant', '13', 'Medium', 'undead', 'Vampire Warlock - Variant'),
		('vampiric-knight', '11', 'Medium', 'undead', 'Vampiric Knight'),
		('vanara', '2', 'Medium', 'humanoid', 'Vanara'),
		('vapor-lynx', '5', 'Large', 'monstrosity', 'Vapor Lynx'),
		('vellso', '7', 'Medium', 'fiend', 'Vellso'),
		('venom-elemental', '4', 'Large', 'elemental', 'Venom Elemental'),
		('venom-maw-hydra', '12', 'Huge', 'monstrosity', 'Venom Maw Hydra'),
		('venomous-mummy', '3', 'Medium', 'undead', 'Venomous Mummy'),
		('vesiculosa', '11', 'Gargantuan', 'plant', 'Vesiculosa'),
		('veteran', '3', 'Medium', 'humanoid', 'Veteran'),
		('vila', '5', 'Medium', 'fey', 'Vila'),
		('vile-barber', '2', 'Small', 'fey', 'Vile Barber'),
		('vine-lord', '7', 'Medium', 'plant', 'Vine Lord'),
		('vine-lords-tendril-puppet', '2', 'Medium', 'plant', 'Vine Lord''s Tendril Puppet'),
		('vine-troll-skeleton', '9', 'Large', 'plant', 'Vine Troll Skeleton'),
		('vines-of-nemthyr', '8', 'Large', 'plant', 'Vines of Nemthyr'),
		('violet-fungus', '1/4', 'Medium', 'plant', 'Violet Fungus'),
		('void-dragon-wyrmling', '2', 'Medium', 'dragon', 'Void Dragon Wyrmling'),
		('void-giant', '11', 'Huge', 'giant', 'Void Giant'),
		('voidling', '11', 'Large', 'aberration', 'Voidling'),
		('vrock', '6', 'Large', 'fiend', 'Vrock'),
		('vulture', '0', 'Medium', 'beast', 'Vulture'),
		('wampus-cat', '1', 'Medium', 'monstrosity', 'Wampus Cat'),
		('war-machine-golem', '18', 'Gargantuan', 'construct', 'War Machine Golem'),
		('war-wyvern', '7', 'Large', 'dragon', 'War Wyvern'),
		('warhorse', '1/2', 'Large', 'beast', 'Warhorse');