DROP DATABASE capstone;
    CREATE DATABASE capstone;
    \connect capstone;
    
    CREATE TABLE users (
        username VARCHAR(25) PRIMARY KEY,
        password TEXT NOT NULL,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL
    );
    CREATE TABLE monsters (
        name TEXT PRIMARY KEY,
        cr VARCHAR(5) NOT NULL,
        size VARCHAR(10) NOT NULL,
        type VARCHAR(30) NOT NULL,
        url TEXT NOT NULL
    );
    CREATE TABLE encounters (
        id SERIAL PRIMARY KEY,
        username VARCHAR(25) REFERENCES users ON DELETE CASCADE,
        description TEXT
    );
    CREATE TABLE monster_encounters(
        monster_name TEXT REFERENCES monsters ON DELETE CASCADE,
        encounter_id INTEGER REFERENCES encounters ON DELETE CASCADE,
        number_of INTEGER NOT NULL
    );
    CREATE TABLE user_encounters (
        id SERIAL PRIMARY KEY,
        encounter_id INTEGER REFERENCES encounters ON DELETE CASCADE,
        monster_name TEXT REFERENCES monsters ON DELETE CASCADE
    );
    INSERT INTO users (username, password, first_name, last_name)
    VALUES ('testuser',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'User');
    INSERT INTO monsters (name, cr, size, type, url)
    VALUES ('Aatxe', '5', 'Large', 'celestial', 'aatxe'),
		('Aboleth', '10', 'Large', 'aberration', 'aboleth'),
		('Aboleth, Nihilith', '12', 'Large', 'undead', 'aboleth-nihilith'),
		('Abominable Beauty', '11', 'Medium', 'fey', 'abominable-beauty'),
		('Accursed Defiler', '4', 'Medium', 'undead', 'accursed-defiler'),
		('Acid Ant', '1/4', 'Small', 'monstrosity', 'acid-ant'),
		('Acolyte', '1/4', 'Medium', 'humanoid', 'acolyte'),
		('Adult Black Dragon', '14', 'Huge', 'dragon', 'adult-black-dragon'),
		('Adult Blue Dragon', '16', 'Huge', 'dragon', 'adult-blue-dragon'),
		('Adult Brass Dragon', '13', 'Huge', 'dragon', 'adult-brass-dragon'),
		('Adult Bronze Dragon', '15', 'Huge', 'dragon', 'adult-bronze-dragon'),
		('Adult Cave Dragon', '16', 'Huge', 'dragon', 'adult-cave-dragon'),
		('Adult Copper Dragon', '14', 'Huge', 'dragon', 'adult-copper-dragon'),
		('Adult Flame Dragon', '16', 'Huge', 'dragon', 'adult-flame-dragon'),
		('Adult Gold Dragon', '17', 'Huge', 'dragon', 'adult-gold-dragon'),
		('Adult Green Dragon', '15', 'Huge', 'dragon', 'adult-green-dragon'),
		('Adult Light Dragon', '16', 'Huge', 'dragon', 'adult-light-dragon'),
		('Adult Mithral Dragon', '14', 'Huge', 'dragon', 'adult-mithral-dragon'),
		('Adult Red Dragon', '17', 'Huge', 'dragon', 'adult-red-dragon'),
		('Adult Rime Worm', '6', 'Large', 'elemental', 'adult-rime-worm'),
		('Adult Sea Dragon', '16', 'Huge', 'dragon', 'adult-sea-dragon'),
		('Adult Silver Dragon', '16', 'Huge', 'dragon', 'adult-silver-dragon'),
		('Adult Void Dragon', '14', 'Huge', 'dragon', 'adult-void-dragon'),
		('Adult Wasteland Dragon', '17', 'Huge', 'dragon', 'adult-wasteland-dragon'),
		('Adult White Dragon', '13', 'Huge', 'dragon', 'adult-white-dragon'),
		('Adult Wind Dragon', '17', 'Huge', 'dragon', 'adult-wind-dragon'),
		('Agnibarra', '1', 'Small', 'monstrosity', 'agnibarra'),
		('Ahu-Nixta', '3', 'Large', 'aberration', 'ahu-nixta'),
		('Ahuizotl', '2', 'Small', 'monstrosity', 'ahuizotl'),
		('Air Elemental', '5', 'Large', 'elemental', 'air-elemental'),
		('Akyishigal, Demon Lord Of Cockroaches', '12', 'Large', 'fiend', 'akyishigal-demon-lord-of-cockroaches'),
		('Al-Aeshma Genie', '9', 'Large', 'elemental', 'al-aeshma-genie'),
		('Ala', '8', 'Medium', 'fey', 'ala'),
		('Alabaster Tree', '7', 'Huge', 'celestial', 'alabaster-tree'),
		('Albino Death Weasel', '1', 'Large', 'beast', 'albino-death-weasel'),
		('Alchemical Apprentice', '1', 'Small', 'ooze', 'alchemical-apprentice'),
		('Alchemical Golem', '9', 'Large', 'construct', 'alchemical-golem'),
		('Alchemist Archer', '10', 'Medium', 'humanoid', 'alchemist-archer'),
		('Alehouse Drake', '1/2', 'Tiny', 'dragon', 'alehouse-drake'),
		('Algorith', '10', 'Medium', 'construct', 'algorith'),
		('Alkonost', '1/2', 'Small', 'monstrosity', 'alkonost'),
		('Alliumite', '1/4', 'Small', 'plant', 'alliumite'),
		('Alnaar', '9', 'Large', 'fiend', 'alnaar'),
		('Alp', '1', 'Small', 'fey', 'alp'),
		('Alpha Yek', '9', 'Medium', 'fiend', 'alpha-yek'),
		('Alquam, Demon Lord Of Night', '21', 'Huge', 'fiend', 'alquam-demon-lord-of-night'),
		('Alseid', '1/2', 'Medium', 'monstrosity', 'alseid'),
		('Alseid Grovekeeper', '3', 'Medium', 'monstrosity', 'alseid-grovekeeper'),
		('Altar Flame Golem', '10', 'Large', 'construct', 'altar-flame-golem'),
		('Ammut', '9', 'Large', 'celestial', 'ammut'),
		('Amphiptere', '3', 'Medium', 'beast', 'amphiptere'),
		('Ancient Black Dragon', '21', 'Gargantuan', 'dragon', 'ancient-black-dragon'),
		('Ancient Blue Dragon', '23', 'Gargantuan', 'dragon', 'ancient-blue-dragon'),
		('Ancient Brass Dragon', '20', 'Gargantuan', 'dragon', 'ancient-brass-dragon'),
		('Ancient Bronze Dragon', '22', 'Gargantuan', 'dragon', 'ancient-bronze-dragon'),
		('Ancient Copper Dragon', '21', 'Gargantuan', 'dragon', 'ancient-copper-dragon'),
		('Ancient Flame Dragon', '24', 'Gargantuan', 'dragon', 'ancient-flame-dragon'),
		('Ancient Gold Dragon', '24', 'Gargantuan', 'dragon', 'ancient-gold-dragon'),
		('Ancient Green Dragon', '22', 'Gargantuan', 'dragon', 'ancient-green-dragon'),
		('Ancient Light Dragon', '22', 'Gargantuan', 'dragon', 'ancient-light-dragon'),
		('Ancient Mandriano', '8', 'Huge', 'plant', 'ancient-mandriano'),
		('Ancient Mithral Dragon', '18', 'Gargantuan', 'dragon', 'ancient-mithral-dragon'),
		('Ancient Red Dragon', '24', 'Gargantuan', 'dragon', 'ancient-red-dragon'),
		('Ancient Sea Dragon', '22', 'Gargantuan', 'dragon', 'ancient-sea-dragon'),
		('Ancient Silver Dragon', '23', 'Gargantuan', 'dragon', 'ancient-silver-dragon'),
		('Ancient Titan', '12', 'Gargantuan', 'celestial', 'ancient-titan'),
		('Ancient Void Dragon', '24', 'Gargantuan', 'dragon', 'ancient-void-dragon'),
		('Ancient Wasteland Dragon', '23', 'Gargantuan', 'dragon', 'ancient-wasteland-dragon'),
		('Ancient White Dragon', '20', 'Gargantuan', 'dragon', 'ancient-white-dragon'),
		('Ancient Wind Dragon', '22', 'Gargantuan', 'dragon', 'ancient-wind-dragon'),
		('Andrenjinyi', '15', 'Gargantuan', 'celestial', 'andrenjinyi'),
		('Androsphinx', '17', 'Large', 'monstrosity', 'androsphinx'),
		('Angatra', '6', 'Medium', 'undead', 'angatra'),
		('Angel, Chained', '8', 'Medium', 'celestial', 'angel-chained'),
		('Angler Worm', '4', 'Huge', 'monstrosity', 'angler-worm'),
		('Animated Armor', '1', 'Medium', 'construct', 'animated-armor'),
		('Ankheg', '2', 'Large', 'monstrosity', 'ankheg'),
		('Ankou Soul Herald', '21', 'Gargantuan', 'dragon', 'ankou-soul-herald'),
		('Ankou Soul Seeker', '8', 'Large', 'dragon', 'ankou-soul-seeker'),
		('Anophiloi', '1', 'Small', 'monstrosity', 'anophiloi'),
		('Anubian', '2', 'Medium', 'elemental', 'anubian'),
		('Apau Perape', '6', 'Large', 'fiend', 'apau-perape'),
		('Ape', '1/2', 'Medium', 'beast', 'ape'),
		('Arbeyach', '21', 'Large', 'fiend', 'arbeyach'),
		('Arborcyte', '8', 'Large', 'plant', 'arborcyte'),
		('Arboreal Grappler', '3', 'Medium', 'aberration', 'arboreal-grappler'),
		('Arcamag', '2', 'Tiny', 'monstrosity', 'arcamag'),
		('Arcanaphage', '4', 'Medium', 'monstrosity', 'arcanaphage'),
		('Archaeopteryx', '1/4', 'Tiny', 'beast', 'archaeopteryx'),
		('Archmage', '12', 'Medium', 'humanoid', 'archmage'),
		('Aridni', '5', 'Small', 'fey', 'aridni'),
		('Armory Golem', '7', 'Large', 'construct', 'armory-golem'),
		('Asanbosam', '5', 'Large', 'aberration', 'asanbosam'),
		('Ash Drake', '4', 'Small', 'dragon', 'ash-drake'),
		('Assassin', '8', 'Medium', 'humanoid', 'assassin'),
		('Astral Snapper', '3', 'Medium', 'aberration', 'astral-snapper'),
		('Automata Devil', '10', 'Large', 'fiend', 'automata-devil'),
		('Avatar Of Boreas', '17', 'Medium', 'elemental', 'avatar-of-boreas'),
		('Avatar of Shoth', '21', 'Gargantuan', 'aberration', 'avatar-of-shoth'),
		('Awakened Shrub', '0', 'Small', 'plant', 'awakened-shrub'),
		('Awakened Tree', '2', 'Huge', 'plant', 'awakened-tree'),
		('Axe Beak', '1/4', 'Large', 'beast', 'axe-beak'),
		('Azeban', '4', 'Medium', 'fey', 'azeban'),
		('Azer', '2', 'Medium', 'elemental', 'azer'),
		('Azi Dahaka', '14', 'Huge', 'dragon', 'azi-dahaka'),
		('Azza Gremlin', '1/4', 'Small', 'fey', 'azza-gremlin'),
		('Baba Yaga''s Horsemen, Black Night', '11', 'Medium', 'fey', 'baba-yagas-horsemen-black-night'),
		('Baba Yaga''s Horsemen, Bright Day', '11', 'Medium', 'fey', 'baba-yagas-horsemen-bright-day'),
		('Baba Yaga''s Horsemen, Red Sun', '11', 'Medium', 'fey', 'baba-yagas-horsemen-red-sun'),
		('Baboon', '0', 'Small', 'beast', 'baboon'),
		('Badger', '0', 'Tiny', 'beast', 'badger'),
		('Bagiennik', '3', 'Medium', 'aberration', 'bagiennik'),
		('Balor', '19', 'Huge', 'fiend', 'balor'),
		('Bandit', '1/8', 'Medium', 'humanoid', 'bandit'),
		('Bandit Captain', '2', 'Medium', 'humanoid', 'bandit-captain'),
		('Bandit Lord', '4', 'Medium', 'Humanoid (Any Race)', 'bandit-lord'),
		('Bar Brawl', '3', 'Huge', 'humanoids', 'bar-brawl'),
		('Barbed Devil', '5', 'Medium', 'fiend', 'barbed-devil'),
		('Barong', '17', 'Large', 'celestial', 'barong'),
		('Basilisk', '3', 'Medium', 'monstrosity', 'basilisk'),
		('Bastet Temple Cat', '1', 'Small', 'monstrosity', 'bastet-temple-cat'),
		('Bat', '0', 'Tiny', 'beast', 'bat'),
		('Bathhouse Drake', '3', 'Medium', 'dragon', 'bathhouse-drake'),
		('Bear King', '12', 'Medium', 'fey', 'bear-king'),
		('Bearded Devil', '3', 'Medium', 'fiend', 'bearded-devil'),
		('Bearfolk', '3', 'Medium', 'humanoid', 'bearfolk'),
		('Bearfolk Chieftain', '6', 'Medium', 'humanoid', 'bearfolk-chieftain'),
		('Bearmit Crab', '2', 'Large', 'monstrosity', 'bearmit-crab'),
		('Beggar Ghoul', '1/2', 'Medium', 'undead', 'beggar-ghoul'),
		('Behir', '11', 'Huge', 'monstrosity', 'behir'),
		('Behtu', '2', 'Small', 'humanoid', 'behtu'),
		('Beli', '2', 'Small', 'fey', 'beli'),
		('Bereginyas', '4', 'Tiny', 'fey', 'bereginyas'),
		('Berserker', '2', 'Medium', 'humanoid', 'berserker'),
		('Berstuc', '11', 'Large', 'fiend', 'berstuc'),
		('Bilwis', '1', 'Medium', 'elemental', 'bilwis'),
		('Black Bear', '1/2', 'Medium', 'beast', 'black-bear'),
		('Black Dragon Wyrmling', '2', 'Medium', 'dragon', 'black-dragon-wyrmling'),
		('Black Knight Commander', '5', 'Medium', 'Humanoid (Any Race)', 'black-knight-commander'),
		('Black Pudding', '4', 'Large', 'ooze', 'black-pudding'),
		('Black Sun Orc', '2', 'Medium', 'humanoid', 'black-sun-orc'),
		('Black Sun Priestess', '3', 'Medium', 'humanoid', 'black-sun-priestess'),
		('Blemmyes', '8', 'Large', 'monstrosity', 'blemmyes'),
		('Blink Dog', '1/4', 'Medium', 'fey', 'blink-dog'),
		('Blood Elemental', '5', 'Large', 'elemental', 'blood-elemental'),
		('Blood Giant', '8', 'Huge', 'giant', 'blood-giant'),
		('Blood Hag', '11', 'Medium', 'fey', 'blood-hag'),
		('Blood Hawk', '1/8', 'Small', 'beast', 'blood-hawk'),
		('Blood Ooze', '6', 'Large', 'ooze', 'blood-ooze'),
		('Blood Zombie', '2', 'Medium', 'undead', 'blood-zombie'),
		('Bloody Bones', '3', 'Medium', 'monstrosity', 'bloody-bones'),
		('Blue Dragon Wyrmling', '3', 'Medium', 'dragon', 'blue-dragon-wyrmling'),
		('Boar', '1/4', 'Medium', 'beast', 'boar'),
		('Boloti', '1', 'Tiny', 'fey', 'boloti'),
		('Bone Collective', '8', 'Small', 'undead', 'bone-collective'),
		('Bone Crab', '1/2', 'Small', 'beast', 'bone-crab'),
		('Bone Devil', '12', 'Large', 'fiend', 'bone-devil'),
		('Bone Golem', '7', 'Medium', 'construct', 'bone-golem'),
		('Bone Swarm', '10', 'Large', 'swarm of Tiny undead', 'bone-swarm'),
		('Bonepowder Ghoul', '12', 'Small', 'undead', 'bonepowder-ghoul'),
		('Bookkeeper', '1/8', 'Tiny', 'construct', 'bookkeeper'),
		('Boot Grabber', '1/2', 'Small', 'aberration', 'boot-grabber'),
		('Bouda', '5', 'Medium', 'fiend', 'bouda'),
		('Brass Dragon Wyrmling', '1', 'Medium', 'dragon', 'brass-dragon-wyrmling'),
		('Bronze Dragon Wyrmling', '2', 'Medium', 'dragon', 'bronze-dragon-wyrmling'),
		('Bronze Golem', '3', 'Large', 'construct', 'bronze-golem'),
		('Broodiken', '1', 'Tiny', 'construct', 'broodiken'),
		('Brown Bear', '1', 'Large', 'beast', 'brown-bear'),
		('Bucca', '1/2', 'Tiny', 'fey', 'bucca'),
		('Bugbear', '1', 'Medium', 'humanoid', 'bugbear'),
		('Bukavac', '9', 'Large', 'monstrosity', 'bukavac'),
		('Bulette', '5', 'Large', 'monstrosity', 'bulette'),
		('Buraq', '11', 'Medium', 'celestial', 'buraq'),
		('Burrowling', '1/2', 'Small', 'humanoid', 'burrowling'),
		('Cactid', '3', 'Large', 'plant', 'cactid'),
		('Cacus Giant', '6', 'Huge', 'giant', 'cacus-giant'),
		('Camazotz, Demon Lord Of Bats And Fire', '22', 'Large', 'fiend', 'camazotz-demon-lord-of-bats-and-fire'),
		('Cambium', '14', 'Large', 'fiend', 'cambium'),
		('Camel', '1/8', 'Large', 'beast', 'camel'),
		('Carbuncle', '1', 'Small', 'monstrosity', 'carbuncle'),
		('Carrion Beetle', '4', 'Large', 'beast', 'carrion-beetle'),
		('Cat', '0', 'Tiny', 'beast', 'cat'),
		('Cats of Ulthar', '4', 'Huge', 'beasts', 'cats-of-ulthar'),
		('Cauldronborn', '2', 'Small', 'construct', 'cauldronborn'),
		('Cave Dragon Wyrmling', '2', 'Medium', 'dragon', 'cave-dragon-wyrmling'),
		('Cave Giant', '10', 'Huge', 'giant', 'cave-giant'),
		('Cavelight Moss', '4', 'Large', 'plant', 'cavelight-moss'),
		('Centaur', '2', 'Large', 'monstrosity', 'centaur'),
		('Centaur Chieftain', '5', 'Large', 'monstrosity', 'centaur-chieftain'),
		('Chain Devil', '11', 'Medium', 'fiend', 'chain-devil'),
		('Chaos-Spawn Goblin', '1/2', 'Small', 'humanoid', 'chaos-spawn-goblin'),
		('Chelicerae', '7', 'Large', 'aberration', 'chelicerae'),
		('Chernomoi', '1', 'Tiny', 'fey', 'chernomoi'),
		('Child Of The Briar', '1', 'Tiny', 'plant', 'child-of-the-briar'),
		('Child of Yggdrasil', '6', 'Large', 'aberration', 'child-of-yggdrasil'),
		('Chimera', '6', 'Large', 'monstrosity', 'chimera'),
		('Chort Devil', '12', 'Medium', 'fiend', 'chort-devil'),
		('Chronalmental', '8', 'Large', 'elemental', 'chronalmental'),
		('Chuhaister', '7', 'Large', 'giant', 'chuhaister'),
		('Chupacabra', '1/2', 'Small', 'monstrosity', 'chupacabra'),
		('Chuul', '4', 'Large', 'aberration', 'chuul'),
		('Cikavak', '1/8', 'Tiny', 'fey', 'cikavak'),
		('Cipactli', '5', 'Medium', 'fiend', 'cipactli'),
		('City Watch Captain', '4', 'Medium', 'Humanoid (Any Race)', 'city-watch-captain'),
		('Clacking Skeleton', '2', 'Medium', 'undead', 'clacking-skeleton'),
		('Clay Golem', '9', 'Large', 'construct', 'clay-golem'),
		('Cloaker', '8', 'Large', 'aberration', 'cloaker'),
		('Clockwork Abomination', '5', 'Large', 'construct', 'clockwork-abomination'),
		('Clockwork Assassin', '6', 'Medium', 'construct', 'clockwork-assassin'),
		('Clockwork Beetle', '1/2', 'Tiny', 'construct', 'clockwork-beetle'),
		('Clockwork Beetle Swarm', '3', 'Large', 'Swarm of Tiny constructs', 'clockwork-beetle-swarm'),
		('Clockwork Hound', '2', 'Medium', 'construct', 'clockwork-hound'),
		('Clockwork Huntsman', '3', 'Medium', 'construct', 'clockwork-huntsman'),
		('Clockwork Myrmidon', '6', 'Large', 'construct', 'clockwork-myrmidon'),
		('Clockwork Servant', '1/8', 'Medium', 'construct', 'clockwork-servant'),
		('Clockwork Soldier', '1', 'Medium', 'construct', 'clockwork-soldier'),
		('Clockwork Watchman', '1/2', 'Medium', 'construct', 'clockwork-watchman'),
		('Cloud Giant', '9', 'Huge', 'giant', 'cloud-giant'),
		('Clurichaun', '1/4', 'Tiny', 'fey', 'clurichaun'),
		('Cobbleswarm', '2', 'Medium', 'swarm of Tiny monstrosities', 'cobbleswarm'),
		('Cockatrice', '1/2', 'Small', 'monstrosity', 'cockatrice'),
		('Commoner', '0', 'Medium', 'humanoid', 'commoner'),
		('Constrictor Snake', '1/4', 'Large', 'beast', 'constrictor-snake'),
		('Copper Dragon Wyrmling', '1', 'Medium', 'dragon', 'copper-dragon-wyrmling'),
		('Coral Drake', '7', 'Medium', 'dragon', 'coral-drake'),
		('Corpse Mound', '11', 'Huge', 'undead', 'corpse-mound'),
		('Corpse Thief', '1/2', 'Medium', 'humanoid', 'corpse-thief'),
		('Corrupting Ooze', '5', 'Large', 'ooze', 'corrupting-ooze'),
		('Couatl', '4', 'Medium', 'celestial', 'couatl'),
		('Crab', '0', 'Tiny', 'beast', 'crab'),
		('Crimson Drake', '1', 'Tiny', 'dragon', 'crimson-drake'),
		('Crimson Mist', '6', 'Medium', 'undead', 'crimson-mist'),
		('Crocodile', '1/2', 'Large', 'beast', 'crocodile'),
		('Crypt Spider', '2', 'Medium', 'beast', 'crypt-spider'),
		('Crystalline Devil', '6', 'Medium', 'fiend', 'crystalline-devil'),
		('Cueyatl', '1/2', 'Small', 'humanoid', 'cueyatl'),
		('Cueyatl Moon Priest', '5', 'Small', 'humanoid', 'cueyatl-moon-priest'),
		('Cueyatl Sea Priest', '1', 'Small', 'humanoid', 'cueyatl-sea-priest'),
		('Cueyatl Warrior', '1', 'Small', 'humanoid', 'cueyatl-warrior'),
		('Cult Fanatic', '2', 'Medium', 'humanoid', 'cult-fanatic'),
		('Cultist', '1/8', 'Medium', 'humanoid', 'cultist'),
		('Darakhul High Priestess', '9', 'Medium', 'undead', 'darakhul-high-priestess'),
		('Darakhul Shadowmancer', '4', 'Medium', 'undead', 'darakhul-shadowmancer'),
		('Dark Eye', '3', 'Medium', 'humanoid', 'dark-eye'),
		('Dark Father', '4', 'Large', 'undead', 'dark-father'),
		('Dark Servant', '1', 'Medium', 'humanoid', 'dark-servant'),
		('Dark Voice', '5', 'Medium', 'humanoid', 'dark-voice'),
		('Darkmantle', '1/2', 'Small', 'monstrosity', 'darkmantle'),
		('Dau', '4', 'Small', 'fey', 'dau'),
		('Death Butterfly Swarm', '4', 'Large', 'swarm of tiny beasts', 'death-butterfly-swarm'),
		('Death Dog', '1', 'Medium', 'monstrosity', 'death-dog'),
		('Deathcap Myconid', '4', 'Medium', 'plant', 'deathcap-myconid'),
		('Deathsworn Elf', '6', 'Medium', 'humanoid', 'deathsworn-elf'),
		('Deathwisp', '7', 'Medium', 'undead', 'deathwisp'),
		('Deep Drake', '9', 'Large', 'dragon', 'deep-drake'),
		('Deep Gnome (Svirfneblin)', '1/2', 'Small', 'humanoid', 'deep-gnome-svirfneblin'),
		('Deep One', '2', 'Medium', 'humanoid', 'deep-one'),
		('Deep One Archimandrite', '8', 'Large', 'humanoid', 'deep-one-archimandrite'),
		('Deep One Hybrid Priest', '4', 'Medium', 'humanoid', 'deep-one-hybrid-priest'),
		('Deer', '0', 'Medium', 'beast', 'deer'),
		('Degenerate Titan', '8', 'Huge', 'giant', 'degenerate-titan'),
		('Derro Fetal Savant', '4', 'Tiny', 'humanoid', 'derro-fetal-savant'),
		('Derro Shadow Antipaladin', '5', 'Small', 'humanoid', 'derro-shadow-antipaladin'),
		('Desert Giant', '9', 'Huge', 'giant', 'desert-giant'),
		('Desert Troll', '6', 'Large', 'giant', 'desert-troll'),
		('Deva', '10', 'Medium', 'celestial', 'deva'),
		('Devil Bough', '6', 'Huge', 'fiend', 'devil-bough'),
		('Devil Shark', '13', 'Gargantuan', 'monstrosity', 'devil-shark'),
		('Devilbound Gnomish Prince', '9', 'Small', 'Humanoid', 'devilbound-gnomish-prince'),
		('Dhampir', '1', 'Medium', 'humanoid', 'dhampir'),
		('Dhampir Commander', '7', 'Medium', 'humanoid', 'dhampir-commander'),
		('Dipsa', '1/4', 'Tiny', 'ooze', 'dipsa'),
		('Dire Wolf', '1', 'Large', 'beast', 'dire-wolf'),
		('Dissimortuum', '7', 'Medium', 'undead', 'dissimortuum'),
		('Djinni', '11', 'Large', 'elemental', 'djinni'),
		('Dogmole', '1', 'Medium', 'beast', 'dogmole'),
		('Dogmole Juggernaut', '5', 'Large', 'monstrosity', 'dogmole-juggernaut'),
		('Domovoi', '4', 'Medium', 'fey', 'domovoi'),
		('Doom Golem', '10', 'Large', 'construct', 'doom-golem'),
		('Doppelganger', '3', 'Medium', 'monstrosity', 'doppelganger'),
		('Doppelrat', '2', 'Tiny', 'monstrosity', 'doppelrat'),
		('Dorreq', '4', 'Medium', 'aberration', 'dorreq'),
		('Dracotaur', '6', 'Large', 'dragon', 'dracotaur'),
		('Draft Horse', '1/4', 'Large', 'beast', 'draft-horse'),
		('Dragon Eel', '12', 'Huge', 'dragon', 'dragon-eel'),
		('Dragon Turtle', '17', 'Gargantuan', 'dragon', 'dragon-turtle'),
		('Dragonleaf Tree', '8', 'Large', 'plant', 'dragonleaf-tree'),
		('Drakon', '5', 'Large', 'beast', 'drakon'),
		('Dream Eater', '5', 'Medium', 'fiend', 'dream-eater'),
		('Dream Squire', '2', 'Medium', 'fey', 'dream-squire'),
		('Dream Wraith', '5', 'Medium', 'undead', 'dream-wraith'),
		('Dretch', '1/4', 'Small', 'fiend', 'dretch'),
		('Drider', '6', 'Large', 'monstrosity', 'drider'),
		('Droth', '12', 'Huge', 'aberration', 'droth'),
		('Drow', '1/4', 'Medium', 'humanoid', 'drow'),
		('Drowned Maiden', '5', 'Medium', 'undead', 'drowned-maiden'),
		('Druid', '2', 'Medium', 'humanoid', 'druid'),
		('Dryad', '1', 'Medium', 'fey', 'dryad'),
		('Duergar', '1', 'Medium', 'humanoid', 'duergar'),
		('Dullahan', '11', 'Large', 'fey', 'dullahan'),
		('Dune Mimic', '8', 'Huge', 'monstrosity', 'dune-mimic'),
		('Duskthorn Dryad', '3', 'Medium', 'fey', 'duskthorn-dryad'),
		('Dust Goblin', '1/4', 'Small', 'humanoid', 'dust-goblin'),
		('Dust Goblin Chieftain', '3', 'Small', 'humanoid', 'dust-goblin-chieftain'),
		('Dust Mephit', '1/2', 'Small', 'elemental', 'dust-mephit'),
		('Dvarapala', '5', 'Huge', 'giant', 'dvarapala'),
		('Dwarven Ringmage', '7', 'Medium', 'Humanoid', 'dwarven-ringmage'),
		('Eagle', '0', 'Small', 'beast', 'eagle'),
		('Eala', '2', 'Small', 'monstrosity', 'eala'),
		('Earth Elemental', '5', 'Large', 'elemental', 'earth-elemental'),
		('Eater Of Dust (Yakat-Shi)', '9', 'Medium', 'aberration', 'eater-of-dust-yakat-shi'),
		('Echo', '6', 'Medium', 'fiend', 'echo'),
		('Ecstatic Bloom', '11', 'Huge', 'celestial', 'ecstatic-bloom'),
		('Edimmu', '4', 'Medium', 'undead', 'edimmu'),
		('Edjet', '3', 'Medium', 'humanoid', 'edjet'),
		('Eel Hound', '2', 'Medium', 'fey', 'eel-hound'),
		('Efreeti', '11', 'Large', 'elemental', 'efreeti'),
		('Einherjar', '7', 'Medium', 'humanoid', 'einherjar'),
		('Elder Ghost Boar', '6', 'Huge', 'monstrosity', 'elder-ghost-boar'),
		('Elder Shadow Drake', '7', 'Large', 'dragon', 'elder-shadow-drake'),
		('Eleinomae', '5', 'Medium', 'fey', 'eleinomae'),
		('Elemental Locus', '17', 'Gargantuan', 'elemental', 'elemental-locus'),
		('Elementalist', '2', 'Medium', 'humanoid', 'elementalist'),
		('Elephant', '4', 'Huge', 'beast', 'elephant'),
		('Elite Kobold', '1', 'Small', 'humanoid', 'elite-kobold'),
		('Elk', '1/4', 'Large', 'beast', 'elk'),
		('Elophar', '4', 'Large', 'undead', 'elophar'),
		('Elvish Veteran Archer', '3', 'Medium', 'Humanoid', 'elvish-veteran-archer'),
		('Emerald Eye', '1', 'Tiny', 'construct', 'emerald-eye'),
		('Emerald Order Cult Leader', '8', 'Medium', 'Humanoid (any race)', 'emerald-order-cult-leader'),
		('Emperor Of The Ghouls', '20', 'Medium', 'undead', 'emperor-of-the-ghouls'),
		('Empty Cloak', '1/2', 'Medium', 'construct', 'empty-cloak'),
		('Enchanter', '7', 'Medium', 'humanoid', 'enchanter'),
		('Eonic Drifter', '1', 'Medium', 'humanoid', 'eonic-drifter'),
		('Erina Defender', '1', 'Small', 'humanoid', 'erina-defender'),
		('Erina Scrounger', '1/4', 'Small', 'humanoid', 'erina-scrounger'),
		('Erinyes', '12', 'Medium', 'fiend', 'erinyes'),
		('Ettercap', '2', 'Medium', 'monstrosity', 'ettercap'),
		('Ettin', '4', 'Large', 'giant', 'ettin'),
		('Execrable Shrub', '1/2', 'Medium', 'fiend', 'execrable-shrub'),
		('Exploding Toad', '1/4', 'Tiny', 'monstrosity', 'exploding-toad'),
		('Eye Golem', '11', 'Large', 'construct', 'eye-golem'),
		('Eye of the Gods', '1', 'Small', 'celestial', 'eye-of-the-gods'),
		('Fang of the Great Wolf', '3', 'Large', 'monstrosity', 'fang-of-the-great-wolf'),
		('Far Darrig', '3', 'Small', 'fey', 'far-darrig'),
		('Far Wanderer', '3', 'Medium', 'aberration', 'far-wanderer'),
		('Fate Eater', '6', 'Medium', 'aberration', 'fate-eater'),
		('Fear Liath', '2', 'Large', 'undead', 'fear-liath'),
		('Fear Smith', '10', 'Medium', 'fey', 'fear-smith'),
		('Fellforged', '5', 'Medium', 'construct', 'fellforged'),
		('Fext', '6', 'Medium', 'undead', 'fext'),
		('Fey Drake', '6', 'Small', 'dragon', 'fey-drake'),
		('Feyward Tree', '8', 'Huge', 'construct', 'feyward-tree'),
		('Fidele Angel', '5', 'Medium', 'celestial', 'fidele-angel'),
		('Fierstjerren', '5', 'Medium', 'undead', 'fierstjerren'),
		('Fire Dancer Swarm', '7', 'Medium', 'swarm of Tiny elementals', 'fire-dancer-swarm'),
		('Fire Elemental', '5', 'Large', 'elemental', 'fire-elemental'),
		('Fire Giant', '9', 'Huge', 'giant', 'fire-giant'),
		('Fire Imp', '1/2', 'Tiny', 'fiend', 'fire-imp'),
		('Firebird', '4', 'Small', 'celestial', 'firebird'),
		('Firegeist', '2', 'Small', 'elemental', 'firegeist'),
		('Flab Giant', '4', 'Large', 'giant', 'flab-giant'),
		('Flame Dragon Wyrmling', '3', 'Medium', 'dragon', 'flame-dragon-wyrmling'),
		('Flame Eater Swarm', '2', 'Medium', 'beasts', 'flame-eater-swarm'),
		('Flame-Scourged Scion', '9', 'Huge', 'aberration', 'flame-scourged-scion'),
		('Flesh Golem', '5', 'Medium', 'construct', 'flesh-golem'),
		('Flesh Reaver', '1/2', 'Medium', 'undead', 'flesh-reaver'),
		('Fleshpod Hornet', '6', 'Large', 'beast', 'fleshpod-hornet'),
		('Flutterflesh', '12', 'Large', 'undead', 'flutterflesh'),
		('Flying Polyp', '11', 'Huge', 'aberration', 'flying-polyp'),
		('Flying Snake', '1/8', 'Tiny', 'beast', 'flying-snake'),
		('Flying Sword', '1/4', 'Small', 'construct', 'flying-sword'),
		('Folk Of Leng', '2', 'Medium', 'humanoid', 'folk-of-leng'),
		('Forest Drake', '2', 'Small', 'dragon', 'forest-drake'),
		('Forest Marauder', '4', 'Large', 'giant', 'forest-marauder'),
		('Foxfire Ooze', '10', 'Large', 'ooze', 'foxfire-ooze'),
		('Foxin', '1/2', 'Small', 'fey', 'foxin'),
		('Fractal Golem', '8', 'Large', 'construct', 'fractal-golem'),
		('Fragrite', '6', 'Medium', 'elemental', 'fragrite'),
		('Fraughashar', '1/2', 'Small', 'fey', 'fraughashar'),
		('Frog', '0', 'Tiny', 'beast', 'frog'),
		('Frost Giant', '8', 'Huge', 'giant', 'frost-giant'),
		('Frostveil', '4', 'Medium', 'plant', 'frostveil'),
		('Fulad-Zereh', '9', 'Huge', 'fiend', 'fulad-zereh'),
		('Fulminar', '9', 'Large', 'elemental', 'fulminar'),
		('Gaki', '8', 'Medium', 'undead', 'gaki'),
		('Gargoctopus', '5', 'Large', 'monstrosity', 'gargoctopus'),
		('Gargoyle', '2', 'Medium', 'elemental', 'gargoyle'),
		('Garroter Crab', '1/4', 'Tiny', 'beast', 'garroter-crab'),
		('Gbahali (Postosuchus)', '6', 'Huge', 'beast', 'gbahali-postosuchus'),
		('Gearforged Templar', '6', 'Medium', 'humanoid', 'gearforged-templar'),
		('Gelatinous Cube', '2', 'Large', 'ooze', 'gelatinous-cube'),
		('Gerridae', '1', 'Large', 'fey', 'gerridae'),
		('Ghast', '2', 'Medium', 'undead', 'ghast'),
		('Ghast of Leng', '3', 'Large', 'aberration', 'ghast-of-leng'),
		('Ghost', '4', 'Medium', 'undead', 'ghost'),
		('Ghost Boar', '3', 'Large', 'monstrosity', 'ghost-boar'),
		('Ghost Dragon', '11', 'Large', 'undead', 'ghost-dragon'),
		('Ghost Dwarf', '6', 'Medium', 'undead', 'ghost-dwarf'),
		('Ghost Knight', '6', 'Medium', 'undead', 'ghost-knight'),
		('Ghostwalk Spider', '9', 'Large', 'monstrosity', 'ghostwalk-spider'),
		('Ghoul', '1', 'Medium', 'undead', 'ghoul'),
		('Ghoul, Darakhul', '3', 'Medium', 'undead', 'ghoul-darakhul'),
		('Ghoul, Imperial', '4', 'Medium', 'undead', 'ghoul-imperial'),
		('Ghoul, Iron', '5', 'Medium', 'undead', 'ghoul-iron'),
		('Ghoulsteed', '3', 'Large', 'undead', 'ghoulsteed'),
		('Giant Albino Bat', '3', 'Huge', 'monstrosity', 'giant-albino-bat'),
		('Giant Ant', '2', 'Large', 'beast', 'giant-ant'),
		('Giant Ant Queen', '4', 'Large', 'beast', 'giant-ant-queen'),
		('Giant Ape', '7', 'Huge', 'beast', 'giant-ape'),
		('Giant Badger', '1/4', 'Medium', 'beast', 'giant-badger'),
		('Giant Bat', '1/4', 'Large', 'beast', 'giant-bat'),
		('Giant Boar', '2', 'Large', 'beast', 'giant-boar'),
		('Giant Centipede', '1/4', 'Small', 'beast', 'giant-centipede'),
		('Giant Constrictor Snake', '2', 'Huge', 'beast', 'giant-constrictor-snake'),
		('Giant Crab', '1/8', 'Medium', 'beast', 'giant-crab'),
		('Giant Crocodile', '5', 'Huge', 'beast', 'giant-crocodile'),
		('Giant Eagle', '1', 'Large', 'beast', 'giant-eagle'),
		('Giant Elk', '2', 'Huge', 'beast', 'giant-elk'),
		('Giant Fire Beetle', '0', 'Small', 'beast', 'giant-fire-beetle'),
		('Giant Frog', '1/4', 'Medium', 'beast', 'giant-frog'),
		('Giant Goat', '1/2', 'Large', 'beast', 'giant-goat'),
		('Giant Hyena', '1', 'Large', 'beast', 'giant-hyena'),
		('Giant Lizard', '1/4', 'Large', 'beast', 'giant-lizard'),
		('Giant Moth', '1/8', 'Small', 'beast', 'giant-moth'),
		('Giant Octopus', '1', 'Large', 'beast', 'giant-octopus'),
		('Giant Owl', '1/4', 'Large', 'beast', 'giant-owl'),
		('Giant Poisonous Snake', '1/4', 'Medium', 'beast', 'giant-poisonous-snake'),
		('Giant Rat', '1/8', 'Small', 'beast', 'giant-rat'),
		('Giant Rat (Diseased)', '1/8', 'Small', 'beast', 'giant-rat-diseased'),
		('Giant Scorpion', '3', 'Large', 'beast', 'giant-scorpion'),
		('Giant Sea Horse', '1/2', 'Large', 'beast', 'giant-sea-horse'),
		('Giant Shark', '5', 'Huge', 'beast', 'giant-shark'),
		('Giant Shark Bowl', '8', 'Huge', 'ooze', 'giant-shark-bowl'),
		('Giant Sloth', '7', 'Large', 'beast', 'giant-sloth'),
		('Giant Spider', '1', 'Large', 'beast', 'giant-spider'),
		('Giant Toad', '1', 'Large', 'beast', 'giant-toad'),
		('Giant Vampire Bat', '2', 'Large', 'beast', 'giant-vampire-bat'),
		('Giant Vulture', '1', 'Large', 'beast', 'giant-vulture'),
		('Giant Wasp', '1/2', 'Medium', 'beast', 'giant-wasp'),
		('Giant Weasel', '1/8', 'Medium', 'beast', 'giant-weasel'),
		('Giant Wolf Spider', '1/4', 'Medium', 'beast', 'giant-wolf-spider'),
		('Gibbering Mouther', '2', 'Medium', 'aberration', 'gibbering-mouther'),
		('Gilded Devil', '7', 'Medium', 'fiend', 'gilded-devil'),
		('Glabrezu', '9', 'Large', 'fiend', 'glabrezu'),
		('Gladiator', '5', 'Medium', 'humanoid', 'gladiator'),
		('Glass Gator', '1', 'Large', 'beast', 'glass-gator'),
		('Glass Golem', '2', 'Small', 'construct', 'glass-golem'),
		('Gloomflower', '3', 'Tiny', 'plant', 'gloomflower'),
		('Gnarljak', '6', 'Small', 'construct', 'gnarljak'),
		('Gnoll', '1/2', 'Medium', 'humanoid', 'gnoll'),
		('Gnoll Havoc Runner', '3', 'Medium', 'humanoid', 'gnoll-havoc-runner'),
		('Gnoll Slaver', '3', 'Medium', 'humanoid', 'gnoll-slaver'),
		('Goat', '0', 'Medium', 'beast', 'goat'),
		('Goat-Man', '3', 'Medium', 'monstrosity', 'goat-man'),
		('Goblin', '1/4', 'Small', 'humanoid', 'goblin'),
		('Gold Dragon Wyrmling', '3', 'Medium', 'dragon', 'gold-dragon-wyrmling'),
		('Goliath Longlegs', '7', 'Gargantuan', 'monstrosity', 'goliath-longlegs'),
		('Goreling', '1/4', 'Small', 'undead', 'goreling'),
		('Gorgon', '5', 'Large', 'monstrosity', 'gorgon'),
		('Grave Behemoth', '10', 'Huge', 'undead', 'grave-behemoth'),
		('Gray Ooze', '1/2', 'Medium', 'ooze', 'gray-ooze'),
		('Gray Thirster', '2', 'Medium', 'undead', 'gray-thirster'),
		('Great Mandrake', '1', 'Tiny', 'plant', 'great-mandrake'),
		('Greater Death Butterfly Swarm', '6', 'Huge', 'swarm of tiny beasts', 'greater-death-butterfly-swarm'),
		('Greater Rakshasa', '15', 'Medium', 'fiend', 'greater-rakshasa'),
		('Greater Scrag', '7', 'Large', 'monstrosity', 'greater-scrag'),
		('Green Abyss Orc', '1/2', 'Medium', 'humanoid', 'green-abyss-orc'),
		('Green Dragon Wyrmling', '2', 'Medium', 'dragon', 'green-dragon-wyrmling'),
		('Green Hag', '3', 'Medium', 'fey', 'green-hag'),
		('Green Knight of the Woods', '6', 'Medium', 'fey', 'green-knight-of-the-woods'),
		('Grick', '2', 'Medium', 'monstrosity', 'grick'),
		('Griffon', '2', 'Large', 'monstrosity', 'griffon'),
		('Grim Jester', '11', 'Medium', 'undead', 'grim-jester'),
		('Grimlock', '1/4', 'Medium', 'humanoid', 'grimlock'),
		('Grindylow', '1', 'Medium', 'aberration', 'grindylow'),
		('Guard', '1/8', 'Medium', 'humanoid', 'guard'),
		('Guardian Naga', '10', 'Large', 'monstrosity', 'guardian-naga'),
		('Gug', '12', 'Huge', 'giant', 'gug'),
		('Gugalanna', '21', 'Huge', 'celestial', 'gugalanna'),
		('Gulon', '6', 'Large', 'monstrosity', 'gulon'),
		('Gumienniki', '1', 'Small', 'fiend', 'gumienniki'),
		('Gynosphinx', '11', 'Large', 'monstrosity', 'gynosphinx'),
		('Gypsosphinx', '14', 'Large', 'monstrosity', 'gypsosphinx'),
		('Hair Golem', '1/4', 'Small', 'construct', 'hair-golem'),
		('Half-Red Dragon Veteran', '5', 'Medium', 'humanoid', 'half-red-dragon-veteran'),
		('Hallowed Reed', '1/2', 'Medium', 'celestial', 'hallowed-reed'),
		('Harpy', '1', 'Medium', 'monstrosity', 'harpy'),
		('Haugbui', '13', 'Medium', 'undead', 'haugbui'),
		('Haunted Giant', '6', 'Huge', 'giant', 'haunted-giant'),
		('Hawk', '0', 'Tiny', 'beast', 'hawk'),
		('Heavy Cavalry', '2', 'Medium', 'humanoid', 'heavy-cavalry'),
		('Hell Hound', '3', 'Medium', 'fiend', 'hell-hound'),
		('Herald Of Blood', '12', 'Huge', 'fiend', 'herald-of-blood'),
		('Herald Of Darkness', '7', 'Large', 'fiend', 'herald-of-darkness'),
		('Hezrou', '8', 'Large', 'fiend', 'hezrou'),
		('Hierophant Lich', '9', 'Medium', 'undead', 'hierophant-lich'),
		('Hill Giant', '5', 'Huge', 'giant', 'hill-giant'),
		('Hippogriff', '1', 'Large', 'monstrosity', 'hippogriff'),
		('Hoard Golem', '12', 'Huge', 'construct', 'hoard-golem');