   
    CREATE TABLE users (
        username VARCHAR(25) PRIMARY KEY,
        password TEXT NOT NULL,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL
    );
    CREATE TABLE monsters (
        slug VARCHAR(50) PRIMARY KEY,
        cr VARCHAR(5) NOT NULL,
        size VARCHAR(10) NOT NULL,
        type VARCHAR(30) NOT NULL,
        name TEXT NOT NULL
    );
    CREATE TABLE encounters (
        id SERIAL PRIMARY KEY,
        username VARCHAR(25) REFERENCES users ON DELETE CASCADE,
        name VARCHAR(25),
        description TEXT
    );
    CREATE TABLE monster_encounters(
        monster_name TEXT REFERENCES monsters ON DELETE CASCADE,
        encounter_id INTEGER REFERENCES encounters ON DELETE CASCADE,
        number_of INTEGER NOT NULL
    );
    INSERT INTO users (username, password, first_name, last_name)
    VALUES ('testuser',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'User');
    INSERT INTO monsters (slug, cr, size, type, name)
    VALUES ('aatxe', '5', 'Large', 'celestial', 'Aatxe'),
		('aboleth', '10', 'Large', 'aberration', 'Aboleth'),
		('aboleth-nihilith', '12', 'Large', 'undead', 'Aboleth, Nihilith'),
		('abominable-beauty', '11', 'Medium', 'fey', 'Abominable Beauty'),
		('accursed-defiler', '4', 'Medium', 'undead', 'Accursed Defiler'),
		('acid-ant', '1/4', 'Small', 'monstrosity', 'Acid Ant'),
		('acolyte', '1/4', 'Medium', 'humanoid', 'Acolyte'),
		('adult-black-dragon', '14', 'Huge', 'dragon', 'Adult Black Dragon'),
		('adult-blue-dragon', '16', 'Huge', 'dragon', 'Adult Blue Dragon'),
		('adult-brass-dragon', '13', 'Huge', 'dragon', 'Adult Brass Dragon'),
		('adult-bronze-dragon', '15', 'Huge', 'dragon', 'Adult Bronze Dragon'),
		('adult-cave-dragon', '16', 'Huge', 'dragon', 'Adult Cave Dragon'),
		('adult-copper-dragon', '14', 'Huge', 'dragon', 'Adult Copper Dragon'),
		('adult-flame-dragon', '16', 'Huge', 'dragon', 'Adult Flame Dragon'),
		('adult-gold-dragon', '17', 'Huge', 'dragon', 'Adult Gold Dragon'),
		('adult-green-dragon', '15', 'Huge', 'dragon', 'Adult Green Dragon'),
		('adult-light-dragon', '16', 'Huge', 'dragon', 'Adult Light Dragon'),
		('adult-mithral-dragon', '14', 'Huge', 'dragon', 'Adult Mithral Dragon'),
		('adult-red-dragon', '17', 'Huge', 'dragon', 'Adult Red Dragon'),
		('adult-rime-worm', '6', 'Large', 'elemental', 'Adult Rime Worm'),
		('adult-sea-dragon', '16', 'Huge', 'dragon', 'Adult Sea Dragon'),
		('adult-silver-dragon', '16', 'Huge', 'dragon', 'Adult Silver Dragon'),
		('adult-void-dragon', '14', 'Huge', 'dragon', 'Adult Void Dragon'),
		('adult-wasteland-dragon', '17', 'Huge', 'dragon', 'Adult Wasteland Dragon'),
		('adult-white-dragon', '13', 'Huge', 'dragon', 'Adult White Dragon'),
		('adult-wind-dragon', '17', 'Huge', 'dragon', 'Adult Wind Dragon'),
		('agnibarra', '1', 'Small', 'monstrosity', 'Agnibarra'),
		('ahu-nixta', '3', 'Large', 'aberration', 'Ahu-Nixta'),
		('ahuizotl', '2', 'Small', 'monstrosity', 'Ahuizotl'),
		('air-elemental', '5', 'Large', 'elemental', 'Air Elemental'),
		('akyishigal-demon-lord-of-cockroaches', '12', 'Large', 'fiend', 'Akyishigal, Demon Lord Of Cockroaches'),
		('al-aeshma-genie', '9', 'Large', 'elemental', 'Al-Aeshma Genie'),
		('ala', '8', 'Medium', 'fey', 'Ala'),
		('alabaster-tree', '7', 'Huge', 'celestial', 'Alabaster Tree'),
		('albino-death-weasel', '1', 'Large', 'beast', 'Albino Death Weasel'),
		('alchemical-apprentice', '1', 'Small', 'ooze', 'Alchemical Apprentice'),
		('alchemical-golem', '9', 'Large', 'construct', 'Alchemical Golem'),
		('alchemist-archer', '10', 'Medium', 'humanoid', 'Alchemist Archer'),
		('alehouse-drake', '1/2', 'Tiny', 'dragon', 'Alehouse Drake'),
		('algorith', '10', 'Medium', 'construct', 'Algorith'),
		('alkonost', '1/2', 'Small', 'monstrosity', 'Alkonost'),
		('alliumite', '1/4', 'Small', 'plant', 'Alliumite'),
		('alnaar', '9', 'Large', 'fiend', 'Alnaar'),
		('alp', '1', 'Small', 'fey', 'Alp'),
		('alpha-yek', '9', 'Medium', 'fiend', 'Alpha Yek'),
		('alquam-demon-lord-of-night', '21', 'Huge', 'fiend', 'Alquam, Demon Lord Of Night'),
		('alseid', '1/2', 'Medium', 'monstrosity', 'Alseid'),
		('alseid-grovekeeper', '3', 'Medium', 'monstrosity', 'Alseid Grovekeeper'),
		('altar-flame-golem', '10', 'Large', 'construct', 'Altar Flame Golem'),
		('ammut', '9', 'Large', 'celestial', 'Ammut'),
		('amphiptere', '3', 'Medium', 'beast', 'Amphiptere'),
		('ancient-black-dragon', '21', 'Gargantuan', 'dragon', 'Ancient Black Dragon'),
		('ancient-blue-dragon', '23', 'Gargantuan', 'dragon', 'Ancient Blue Dragon'),
		('ancient-brass-dragon', '20', 'Gargantuan', 'dragon', 'Ancient Brass Dragon'),
		('ancient-bronze-dragon', '22', 'Gargantuan', 'dragon', 'Ancient Bronze Dragon'),
		('ancient-copper-dragon', '21', 'Gargantuan', 'dragon', 'Ancient Copper Dragon'),
		('ancient-flame-dragon', '24', 'Gargantuan', 'dragon', 'Ancient Flame Dragon'),
		('ancient-gold-dragon', '24', 'Gargantuan', 'dragon', 'Ancient Gold Dragon'),
		('ancient-green-dragon', '22', 'Gargantuan', 'dragon', 'Ancient Green Dragon'),
		('ancient-light-dragon', '22', 'Gargantuan', 'dragon', 'Ancient Light Dragon'),
		('ancient-mandriano', '8', 'Huge', 'plant', 'Ancient Mandriano'),
		('ancient-mithral-dragon', '18', 'Gargantuan', 'dragon', 'Ancient Mithral Dragon'),
		('ancient-red-dragon', '24', 'Gargantuan', 'dragon', 'Ancient Red Dragon'),
		('ancient-sea-dragon', '22', 'Gargantuan', 'dragon', 'Ancient Sea Dragon'),
		('ancient-silver-dragon', '23', 'Gargantuan', 'dragon', 'Ancient Silver Dragon'),
		('ancient-titan', '12', 'Gargantuan', 'celestial', 'Ancient Titan'),
		('ancient-void-dragon', '24', 'Gargantuan', 'dragon', 'Ancient Void Dragon'),
		('ancient-wasteland-dragon', '23', 'Gargantuan', 'dragon', 'Ancient Wasteland Dragon'),
		('ancient-white-dragon', '20', 'Gargantuan', 'dragon', 'Ancient White Dragon'),
		('ancient-wind-dragon', '22', 'Gargantuan', 'dragon', 'Ancient Wind Dragon'),
		('andrenjinyi', '15', 'Gargantuan', 'celestial', 'Andrenjinyi'),
		('androsphinx', '17', 'Large', 'monstrosity', 'Androsphinx'),
		('angatra', '6', 'Medium', 'undead', 'Angatra'),
		('angel-chained', '8', 'Medium', 'celestial', 'Angel, Chained'),
		('angler-worm', '4', 'Huge', 'monstrosity', 'Angler Worm'),
		('animated-armor', '1', 'Medium', 'construct', 'Animated Armor'),
		('ankheg', '2', 'Large', 'monstrosity', 'Ankheg'),
		('ankou-soul-herald', '21', 'Gargantuan', 'dragon', 'Ankou Soul Herald'),
		('ankou-soul-seeker', '8', 'Large', 'dragon', 'Ankou Soul Seeker'),
		('anophiloi', '1', 'Small', 'monstrosity', 'Anophiloi'),
		('anubian', '2', 'Medium', 'elemental', 'Anubian'),
		('apau-perape', '6', 'Large', 'fiend', 'Apau Perape'),
		('ape', '1/2', 'Medium', 'beast', 'Ape'),
		('arbeyach', '21', 'Large', 'fiend', 'Arbeyach'),
		('arborcyte', '8', 'Large', 'plant', 'Arborcyte'),
		('arboreal-grappler', '3', 'Medium', 'aberration', 'Arboreal Grappler'),
		('arcamag', '2', 'Tiny', 'monstrosity', 'Arcamag'),
		('arcanaphage', '4', 'Medium', 'monstrosity', 'Arcanaphage'),
		('archaeopteryx', '1/4', 'Tiny', 'beast', 'Archaeopteryx'),
		('archmage', '12', 'Medium', 'humanoid', 'Archmage'),
		('aridni', '5', 'Small', 'fey', 'Aridni'),
		('armory-golem', '7', 'Large', 'construct', 'Armory Golem'),
		('asanbosam', '5', 'Large', 'aberration', 'Asanbosam'),
		('ash-drake', '4', 'Small', 'dragon', 'Ash Drake'),
		('assassin', '8', 'Medium', 'humanoid', 'Assassin'),
		('astral-snapper', '3', 'Medium', 'aberration', 'Astral Snapper'),
		('automata-devil', '10', 'Large', 'fiend', 'Automata Devil'),
		('avatar-of-boreas', '17', 'Medium', 'elemental', 'Avatar Of Boreas'),
		('avatar-of-shoth', '21', 'Gargantuan', 'aberration', 'Avatar of Shoth'),
		('awakened-shrub', '0', 'Small', 'plant', 'Awakened Shrub'),
		('awakened-tree', '2', 'Huge', 'plant', 'Awakened Tree'),
		('axe-beak', '1/4', 'Large', 'beast', 'Axe Beak'),
		('azeban', '4', 'Medium', 'fey', 'Azeban'),
		('azer', '2', 'Medium', 'elemental', 'Azer'),
		('azi-dahaka', '14', 'Huge', 'dragon', 'Azi Dahaka'),
		('azza-gremlin', '1/4', 'Small', 'fey', 'Azza Gremlin'),
		('baba-yagas-horsemen-black-night', '11', 'Medium', 'fey', 'Baba Yaga''s Horsemen, Black Night'),
		('baba-yagas-horsemen-bright-day', '11', 'Medium', 'fey', 'Baba Yaga''s Horsemen, Bright Day'),
		('baba-yagas-horsemen-red-sun', '11', 'Medium', 'fey', 'Baba Yaga''s Horsemen, Red Sun'),
		('baboon', '0', 'Small', 'beast', 'Baboon'),
		('badger', '0', 'Tiny', 'beast', 'Badger'),
		('bagiennik', '3', 'Medium', 'aberration', 'Bagiennik'),
		('balor', '19', 'Huge', 'fiend', 'Balor'),
		('bandit', '1/8', 'Medium', 'humanoid', 'Bandit'),
		('bandit-captain', '2', 'Medium', 'humanoid', 'Bandit Captain'),
		('bandit-lord', '4', 'Medium', 'Humanoid (Any Race)', 'Bandit Lord'),
		('bar-brawl', '3', 'Huge', 'humanoids', 'Bar Brawl'),
		('barbed-devil', '5', 'Medium', 'fiend', 'Barbed Devil'),
		('barong', '17', 'Large', 'celestial', 'Barong'),
		('basilisk', '3', 'Medium', 'monstrosity', 'Basilisk'),
		('bastet-temple-cat', '1', 'Small', 'monstrosity', 'Bastet Temple Cat'),
		('bat', '0', 'Tiny', 'beast', 'Bat'),
		('bathhouse-drake', '3', 'Medium', 'dragon', 'Bathhouse Drake'),
		('bear-king', '12', 'Medium', 'fey', 'Bear King'),
		('bearded-devil', '3', 'Medium', 'fiend', 'Bearded Devil'),
		('bearfolk', '3', 'Medium', 'humanoid', 'Bearfolk'),
		('bearfolk-chieftain', '6', 'Medium', 'humanoid', 'Bearfolk Chieftain'),
		('bearmit-crab', '2', 'Large', 'monstrosity', 'Bearmit Crab'),
		('beggar-ghoul', '1/2', 'Medium', 'undead', 'Beggar Ghoul'),
		('behir', '11', 'Huge', 'monstrosity', 'Behir'),
		('behtu', '2', 'Small', 'humanoid', 'Behtu'),
		('beli', '2', 'Small', 'fey', 'Beli'),
		('bereginyas', '4', 'Tiny', 'fey', 'Bereginyas'),
		('berserker', '2', 'Medium', 'humanoid', 'Berserker'),
		('berstuc', '11', 'Large', 'fiend', 'Berstuc'),
		('bilwis', '1', 'Medium', 'elemental', 'Bilwis'),
		('black-bear', '1/2', 'Medium', 'beast', 'Black Bear'),
		('black-dragon-wyrmling', '2', 'Medium', 'dragon', 'Black Dragon Wyrmling'),
		('black-knight-commander', '5', 'Medium', 'Humanoid (Any Race)', 'Black Knight Commander'),
		('black-pudding', '4', 'Large', 'ooze', 'Black Pudding'),
		('black-sun-orc', '2', 'Medium', 'humanoid', 'Black Sun Orc'),
		('black-sun-priestess', '3', 'Medium', 'humanoid', 'Black Sun Priestess'),
		('blemmyes', '8', 'Large', 'monstrosity', 'Blemmyes'),
		('blink-dog', '1/4', 'Medium', 'fey', 'Blink Dog'),
		('blood-elemental', '5', 'Large', 'elemental', 'Blood Elemental'),
		('blood-giant', '8', 'Huge', 'giant', 'Blood Giant'),
		('blood-hag', '11', 'Medium', 'fey', 'Blood Hag'),
		('blood-hawk', '1/8', 'Small', 'beast', 'Blood Hawk'),
		('blood-ooze', '6', 'Large', 'ooze', 'Blood Ooze'),
		('blood-zombie', '2', 'Medium', 'undead', 'Blood Zombie'),
		('bloody-bones', '3', 'Medium', 'monstrosity', 'Bloody Bones'),
		('blue-dragon-wyrmling', '3', 'Medium', 'dragon', 'Blue Dragon Wyrmling'),
		('boar', '1/4', 'Medium', 'beast', 'Boar'),
		('boloti', '1', 'Tiny', 'fey', 'Boloti'),
		('bone-collective', '8', 'Small', 'undead', 'Bone Collective'),
		('bone-crab', '1/2', 'Small', 'beast', 'Bone Crab'),
		('bone-devil', '12', 'Large', 'fiend', 'Bone Devil'),
		('bone-golem', '7', 'Medium', 'construct', 'Bone Golem'),
		('bone-swarm', '10', 'Large', 'swarm of Tiny undead', 'Bone Swarm'),
		('bonepowder-ghoul', '12', 'Small', 'undead', 'Bonepowder Ghoul'),
		('bookkeeper', '1/8', 'Tiny', 'construct', 'Bookkeeper'),
		('boot-grabber', '1/2', 'Small', 'aberration', 'Boot Grabber'),
		('bouda', '5', 'Medium', 'fiend', 'Bouda'),
		('brass-dragon-wyrmling', '1', 'Medium', 'dragon', 'Brass Dragon Wyrmling'),
		('bronze-dragon-wyrmling', '2', 'Medium', 'dragon', 'Bronze Dragon Wyrmling'),
		('bronze-golem', '3', 'Large', 'construct', 'Bronze Golem'),
		('broodiken', '1', 'Tiny', 'construct', 'Broodiken'),
		('brown-bear', '1', 'Large', 'beast', 'Brown Bear'),
		('bucca', '1/2', 'Tiny', 'fey', 'Bucca'),
		('bugbear', '1', 'Medium', 'humanoid', 'Bugbear'),
		('bukavac', '9', 'Large', 'monstrosity', 'Bukavac'),
		('bulette', '5', 'Large', 'monstrosity', 'Bulette'),
		('buraq', '11', 'Medium', 'celestial', 'Buraq'),
		('burrowling', '1/2', 'Small', 'humanoid', 'Burrowling'),
		('cactid', '3', 'Large', 'plant', 'Cactid'),
		('cacus-giant', '6', 'Huge', 'giant', 'Cacus Giant'),
		('camazotz-demon-lord-of-bats-and-fire', '22', 'Large', 'fiend', 'Camazotz, Demon Lord Of Bats And Fire'),
		('cambium', '14', 'Large', 'fiend', 'Cambium'),
		('camel', '1/8', 'Large', 'beast', 'Camel'),
		('carbuncle', '1', 'Small', 'monstrosity', 'Carbuncle'),
		('carrion-beetle', '4', 'Large', 'beast', 'Carrion Beetle'),
		('cat', '0', 'Tiny', 'beast', 'Cat'),
		('cats-of-ulthar', '4', 'Huge', 'beasts', 'Cats of Ulthar'),
		('cauldronborn', '2', 'Small', 'construct', 'Cauldronborn'),
		('cave-dragon-wyrmling', '2', 'Medium', 'dragon', 'Cave Dragon Wyrmling'),
		('cave-giant', '10', 'Huge', 'giant', 'Cave Giant'),
		('cavelight-moss', '4', 'Large', 'plant', 'Cavelight Moss'),
		('centaur', '2', 'Large', 'monstrosity', 'Centaur'),
		('centaur-chieftain', '5', 'Large', 'monstrosity', 'Centaur Chieftain'),
		('chain-devil', '11', 'Medium', 'fiend', 'Chain Devil'),
		('chaos-spawn-goblin', '1/2', 'Small', 'humanoid', 'Chaos-Spawn Goblin'),
		('chelicerae', '7', 'Large', 'aberration', 'Chelicerae'),
		('chernomoi', '1', 'Tiny', 'fey', 'Chernomoi'),
		('child-of-the-briar', '1', 'Tiny', 'plant', 'Child Of The Briar'),
		('child-of-yggdrasil', '6', 'Large', 'aberration', 'Child of Yggdrasil'),
		('chimera', '6', 'Large', 'monstrosity', 'Chimera'),
		('chort-devil', '12', 'Medium', 'fiend', 'Chort Devil'),
		('chronalmental', '8', 'Large', 'elemental', 'Chronalmental'),
		('chuhaister', '7', 'Large', 'giant', 'Chuhaister'),
		('chupacabra', '1/2', 'Small', 'monstrosity', 'Chupacabra'),
		('chuul', '4', 'Large', 'aberration', 'Chuul'),
		('cikavak', '1/8', 'Tiny', 'fey', 'Cikavak'),
		('cipactli', '5', 'Medium', 'fiend', 'Cipactli'),
		('city-watch-captain', '4', 'Medium', 'Humanoid (Any Race)', 'City Watch Captain'),
		('clacking-skeleton', '2', 'Medium', 'undead', 'Clacking Skeleton'),
		('clay-golem', '9', 'Large', 'construct', 'Clay Golem'),
		('cloaker', '8', 'Large', 'aberration', 'Cloaker'),
		('clockwork-abomination', '5', 'Large', 'construct', 'Clockwork Abomination'),
		('clockwork-assassin', '6', 'Medium', 'construct', 'Clockwork Assassin'),
		('clockwork-beetle', '1/2', 'Tiny', 'construct', 'Clockwork Beetle'),
		('clockwork-beetle-swarm', '3', 'Large', 'Swarm of Tiny constructs', 'Clockwork Beetle Swarm'),
		('clockwork-hound', '2', 'Medium', 'construct', 'Clockwork Hound'),
		('clockwork-huntsman', '3', 'Medium', 'construct', 'Clockwork Huntsman'),
		('clockwork-myrmidon', '6', 'Large', 'construct', 'Clockwork Myrmidon'),
		('clockwork-servant', '1/8', 'Medium', 'construct', 'Clockwork Servant'),
		('clockwork-soldier', '1', 'Medium', 'construct', 'Clockwork Soldier'),
		('clockwork-watchman', '1/2', 'Medium', 'construct', 'Clockwork Watchman'),
		('cloud-giant', '9', 'Huge', 'giant', 'Cloud Giant'),
		('clurichaun', '1/4', 'Tiny', 'fey', 'Clurichaun'),
		('cobbleswarm', '2', 'Medium', 'swarm of Tiny monstrosities', 'Cobbleswarm'),
		('cockatrice', '1/2', 'Small', 'monstrosity', 'Cockatrice'),
		('commoner', '0', 'Medium', 'humanoid', 'Commoner'),
		('constrictor-snake', '1/4', 'Large', 'beast', 'Constrictor Snake'),
		('copper-dragon-wyrmling', '1', 'Medium', 'dragon', 'Copper Dragon Wyrmling'),
		('coral-drake', '7', 'Medium', 'dragon', 'Coral Drake'),
		('corpse-mound', '11', 'Huge', 'undead', 'Corpse Mound'),
		('corpse-thief', '1/2', 'Medium', 'humanoid', 'Corpse Thief'),
		('corrupting-ooze', '5', 'Large', 'ooze', 'Corrupting Ooze'),
		('couatl', '4', 'Medium', 'celestial', 'Couatl'),
		('crab', '0', 'Tiny', 'beast', 'Crab'),
		('crimson-drake', '1', 'Tiny', 'dragon', 'Crimson Drake'),
		('crimson-mist', '6', 'Medium', 'undead', 'Crimson Mist'),
		('crocodile', '1/2', 'Large', 'beast', 'Crocodile'),
		('crypt-spider', '2', 'Medium', 'beast', 'Crypt Spider'),
		('crystalline-devil', '6', 'Medium', 'fiend', 'Crystalline Devil'),
		('cueyatl', '1/2', 'Small', 'humanoid', 'Cueyatl'),
		('cueyatl-moon-priest', '5', 'Small', 'humanoid', 'Cueyatl Moon Priest'),
		('cueyatl-sea-priest', '1', 'Small', 'humanoid', 'Cueyatl Sea Priest'),
		('cueyatl-warrior', '1', 'Small', 'humanoid', 'Cueyatl Warrior'),
		('cult-fanatic', '2', 'Medium', 'humanoid', 'Cult Fanatic'),
		('cultist', '1/8', 'Medium', 'humanoid', 'Cultist'),
		('darakhul-high-priestess', '9', 'Medium', 'undead', 'Darakhul High Priestess'),
		('darakhul-shadowmancer', '4', 'Medium', 'undead', 'Darakhul Shadowmancer'),
		('dark-eye', '3', 'Medium', 'humanoid', 'Dark Eye'),
		('dark-father', '4', 'Large', 'undead', 'Dark Father'),
		('dark-servant', '1', 'Medium', 'humanoid', 'Dark Servant'),
		('dark-voice', '5', 'Medium', 'humanoid', 'Dark Voice'),
		('darkmantle', '1/2', 'Small', 'monstrosity', 'Darkmantle'),
		('dau', '4', 'Small', 'fey', 'Dau'),
		('death-butterfly-swarm', '4', 'Large', 'swarm of tiny beasts', 'Death Butterfly Swarm'),
		('death-dog', '1', 'Medium', 'monstrosity', 'Death Dog'),
		('deathcap-myconid', '4', 'Medium', 'plant', 'Deathcap Myconid'),
		('deathsworn-elf', '6', 'Medium', 'humanoid', 'Deathsworn Elf'),
		('deathwisp', '7', 'Medium', 'undead', 'Deathwisp'),
		('deep-drake', '9', 'Large', 'dragon', 'Deep Drake'),
		('deep-gnome-svirfneblin', '1/2', 'Small', 'humanoid', 'Deep Gnome (Svirfneblin)'),
		('deep-one', '2', 'Medium', 'humanoid', 'Deep One'),
		('deep-one-archimandrite', '8', 'Large', 'humanoid', 'Deep One Archimandrite'),
		('deep-one-hybrid-priest', '4', 'Medium', 'humanoid', 'Deep One Hybrid Priest'),
		('deer', '0', 'Medium', 'beast', 'Deer'),
		('degenerate-titan', '8', 'Huge', 'giant', 'Degenerate Titan'),
		('derro-fetal-savant', '4', 'Tiny', 'humanoid', 'Derro Fetal Savant'),
		('derro-shadow-antipaladin', '5', 'Small', 'humanoid', 'Derro Shadow Antipaladin'),
		('desert-giant', '9', 'Huge', 'giant', 'Desert Giant'),
		('desert-troll', '6', 'Large', 'giant', 'Desert Troll'),
		('deva', '10', 'Medium', 'celestial', 'Deva'),
		('devil-bough', '6', 'Huge', 'fiend', 'Devil Bough'),
		('devil-shark', '13', 'Gargantuan', 'monstrosity', 'Devil Shark'),
		('devilbound-gnomish-prince', '9', 'Small', 'Humanoid', 'Devilbound Gnomish Prince'),
		('dhampir', '1', 'Medium', 'humanoid', 'Dhampir'),
		('dhampir-commander', '7', 'Medium', 'humanoid', 'Dhampir Commander'),
		('dipsa', '1/4', 'Tiny', 'ooze', 'Dipsa'),
		('dire-wolf', '1', 'Large', 'beast', 'Dire Wolf'),
		('dissimortuum', '7', 'Medium', 'undead', 'Dissimortuum'),
		('djinni', '11', 'Large', 'elemental', 'Djinni'),
		('dogmole', '1', 'Medium', 'beast', 'Dogmole'),
		('dogmole-juggernaut', '5', 'Large', 'monstrosity', 'Dogmole Juggernaut'),
		('domovoi', '4', 'Medium', 'fey', 'Domovoi'),
		('doom-golem', '10', 'Large', 'construct', 'Doom Golem'),
		('doppelganger', '3', 'Medium', 'monstrosity', 'Doppelganger'),
		('doppelrat', '2', 'Tiny', 'monstrosity', 'Doppelrat'),
		('dorreq', '4', 'Medium', 'aberration', 'Dorreq'),
		('dracotaur', '6', 'Large', 'dragon', 'Dracotaur'),
		('draft-horse', '1/4', 'Large', 'beast', 'Draft Horse'),
		('dragon-eel', '12', 'Huge', 'dragon', 'Dragon Eel'),
		('dragon-turtle', '17', 'Gargantuan', 'dragon', 'Dragon Turtle'),
		('dragonleaf-tree', '8', 'Large', 'plant', 'Dragonleaf Tree'),
		('drakon', '5', 'Large', 'beast', 'Drakon'),
		('dream-eater', '5', 'Medium', 'fiend', 'Dream Eater'),
		('dream-squire', '2', 'Medium', 'fey', 'Dream Squire'),
		('dream-wraith', '5', 'Medium', 'undead', 'Dream Wraith'),
		('dretch', '1/4', 'Small', 'fiend', 'Dretch'),
		('drider', '6', 'Large', 'monstrosity', 'Drider'),
		('droth', '12', 'Huge', 'aberration', 'Droth'),
		('drow', '1/4', 'Medium', 'humanoid', 'Drow'),
		('drowned-maiden', '5', 'Medium', 'undead', 'Drowned Maiden'),
		('druid', '2', 'Medium', 'humanoid', 'Druid'),
		('dryad', '1', 'Medium', 'fey', 'Dryad'),
		('duergar', '1', 'Medium', 'humanoid', 'Duergar'),
		('dullahan', '11', 'Large', 'fey', 'Dullahan'),
		('dune-mimic', '8', 'Huge', 'monstrosity', 'Dune Mimic'),
		('duskthorn-dryad', '3', 'Medium', 'fey', 'Duskthorn Dryad'),
		('dust-goblin', '1/4', 'Small', 'humanoid', 'Dust Goblin'),
		('dust-goblin-chieftain', '3', 'Small', 'humanoid', 'Dust Goblin Chieftain'),
		('dust-mephit', '1/2', 'Small', 'elemental', 'Dust Mephit'),
		('dvarapala', '5', 'Huge', 'giant', 'Dvarapala'),
		('dwarven-ringmage', '7', 'Medium', 'Humanoid', 'Dwarven Ringmage'),
		('eagle', '0', 'Small', 'beast', 'Eagle'),
		('eala', '2', 'Small', 'monstrosity', 'Eala'),
		('earth-elemental', '5', 'Large', 'elemental', 'Earth Elemental'),
		('eater-of-dust-yakat-shi', '9', 'Medium', 'aberration', 'Eater Of Dust (Yakat-Shi)'),
		('echo', '6', 'Medium', 'fiend', 'Echo'),
		('ecstatic-bloom', '11', 'Huge', 'celestial', 'Ecstatic Bloom'),
		('edimmu', '4', 'Medium', 'undead', 'Edimmu'),
		('edjet', '3', 'Medium', 'humanoid', 'Edjet'),
		('eel-hound', '2', 'Medium', 'fey', 'Eel Hound'),
		('efreeti', '11', 'Large', 'elemental', 'Efreeti'),
		('einherjar', '7', 'Medium', 'humanoid', 'Einherjar'),
		('elder-ghost-boar', '6', 'Huge', 'monstrosity', 'Elder Ghost Boar'),
		('elder-shadow-drake', '7', 'Large', 'dragon', 'Elder Shadow Drake'),
		('eleinomae', '5', 'Medium', 'fey', 'Eleinomae'),
		('elemental-locus', '17', 'Gargantuan', 'elemental', 'Elemental Locus'),
		('elementalist', '2', 'Medium', 'humanoid', 'Elementalist'),
		('elephant', '4', 'Huge', 'beast', 'Elephant'),
		('elite-kobold', '1', 'Small', 'humanoid', 'Elite Kobold'),
		('elk', '1/4', 'Large', 'beast', 'Elk'),
		('elophar', '4', 'Large', 'undead', 'Elophar'),
		('elvish-veteran-archer', '3', 'Medium', 'Humanoid', 'Elvish Veteran Archer'),
		('emerald-eye', '1', 'Tiny', 'construct', 'Emerald Eye'),
		('emerald-order-cult-leader', '8', 'Medium', 'Humanoid (any race)', 'Emerald Order Cult Leader'),
		('emperor-of-the-ghouls', '20', 'Medium', 'undead', 'Emperor Of The Ghouls'),
		('empty-cloak', '1/2', 'Medium', 'construct', 'Empty Cloak'),
		('enchanter', '7', 'Medium', 'humanoid', 'Enchanter'),
		('eonic-drifter', '1', 'Medium', 'humanoid', 'Eonic Drifter'),
		('erina-defender', '1', 'Small', 'humanoid', 'Erina Defender'),
		('erina-scrounger', '1/4', 'Small', 'humanoid', 'Erina Scrounger'),
		('erinyes', '12', 'Medium', 'fiend', 'Erinyes'),
		('ettercap', '2', 'Medium', 'monstrosity', 'Ettercap'),
		('ettin', '4', 'Large', 'giant', 'Ettin'),
		('execrable-shrub', '1/2', 'Medium', 'fiend', 'Execrable Shrub'),
		('exploding-toad', '1/4', 'Tiny', 'monstrosity', 'Exploding Toad'),
		('eye-golem', '11', 'Large', 'construct', 'Eye Golem'),
		('eye-of-the-gods', '1', 'Small', 'celestial', 'Eye of the Gods'),
		('fang-of-the-great-wolf', '3', 'Large', 'monstrosity', 'Fang of the Great Wolf'),
		('far-darrig', '3', 'Small', 'fey', 'Far Darrig'),
		('far-wanderer', '3', 'Medium', 'aberration', 'Far Wanderer'),
		('fate-eater', '6', 'Medium', 'aberration', 'Fate Eater'),
		('fear-liath', '2', 'Large', 'undead', 'Fear Liath'),
		('fear-smith', '10', 'Medium', 'fey', 'Fear Smith'),
		('fellforged', '5', 'Medium', 'construct', 'Fellforged'),
		('fext', '6', 'Medium', 'undead', 'Fext'),
		('fey-drake', '6', 'Small', 'dragon', 'Fey Drake'),
		('feyward-tree', '8', 'Huge', 'construct', 'Feyward Tree'),
		('fidele-angel', '5', 'Medium', 'celestial', 'Fidele Angel'),
		('fierstjerren', '5', 'Medium', 'undead', 'Fierstjerren'),
		('fire-dancer-swarm', '7', 'Medium', 'swarm of Tiny elementals', 'Fire Dancer Swarm'),
		('fire-elemental', '5', 'Large', 'elemental', 'Fire Elemental'),
		('fire-giant', '9', 'Huge', 'giant', 'Fire Giant'),
		('fire-imp', '1/2', 'Tiny', 'fiend', 'Fire Imp'),
		('firebird', '4', 'Small', 'celestial', 'Firebird'),
		('firegeist', '2', 'Small', 'elemental', 'Firegeist'),
		('flab-giant', '4', 'Large', 'giant', 'Flab Giant'),
		('flame-dragon-wyrmling', '3', 'Medium', 'dragon', 'Flame Dragon Wyrmling'),
		('flame-eater-swarm', '2', 'Medium', 'beasts', 'Flame Eater Swarm'),
		('flame-scourged-scion', '9', 'Huge', 'aberration', 'Flame-Scourged Scion'),
		('flesh-golem', '5', 'Medium', 'construct', 'Flesh Golem'),
		('flesh-reaver', '1/2', 'Medium', 'undead', 'Flesh Reaver'),
		('fleshpod-hornet', '6', 'Large', 'beast', 'Fleshpod Hornet'),
		('flutterflesh', '12', 'Large', 'undead', 'Flutterflesh'),
		('flying-polyp', '11', 'Huge', 'aberration', 'Flying Polyp'),
		('flying-snake', '1/8', 'Tiny', 'beast', 'Flying Snake'),
		('flying-sword', '1/4', 'Small', 'construct', 'Flying Sword'),
		('folk-of-leng', '2', 'Medium', 'humanoid', 'Folk Of Leng'),
		('forest-drake', '2', 'Small', 'dragon', 'Forest Drake'),
		('forest-marauder', '4', 'Large', 'giant', 'Forest Marauder'),
		('foxfire-ooze', '10', 'Large', 'ooze', 'Foxfire Ooze'),
		('foxin', '1/2', 'Small', 'fey', 'Foxin'),
		('fractal-golem', '8', 'Large', 'construct', 'Fractal Golem'),
		('fragrite', '6', 'Medium', 'elemental', 'Fragrite'),
		('fraughashar', '1/2', 'Small', 'fey', 'Fraughashar'),
		('frog', '0', 'Tiny', 'beast', 'Frog'),
		('frost-giant', '8', 'Huge', 'giant', 'Frost Giant'),
		('frostveil', '4', 'Medium', 'plant', 'Frostveil'),
		('fulad-zereh', '9', 'Huge', 'fiend', 'Fulad-Zereh'),
		('fulminar', '9', 'Large', 'elemental', 'Fulminar'),
		('gaki', '8', 'Medium', 'undead', 'Gaki'),
		('gargoctopus', '5', 'Large', 'monstrosity', 'Gargoctopus'),
		('gargoyle', '2', 'Medium', 'elemental', 'Gargoyle'),
		('garroter-crab', '1/4', 'Tiny', 'beast', 'Garroter Crab'),
		('gbahali-postosuchus', '6', 'Huge', 'beast', 'Gbahali (Postosuchus)'),
		('gearforged-templar', '6', 'Medium', 'humanoid', 'Gearforged Templar'),
		('gelatinous-cube', '2', 'Large', 'ooze', 'Gelatinous Cube'),
		('gerridae', '1', 'Large', 'fey', 'Gerridae'),
		('ghast', '2', 'Medium', 'undead', 'Ghast'),
		('ghast-of-leng', '3', 'Large', 'aberration', 'Ghast of Leng'),
		('ghost', '4', 'Medium', 'undead', 'Ghost'),
		('ghost-boar', '3', 'Large', 'monstrosity', 'Ghost Boar'),
		('ghost-dragon', '11', 'Large', 'undead', 'Ghost Dragon'),
		('ghost-dwarf', '6', 'Medium', 'undead', 'Ghost Dwarf'),
		('ghost-knight', '6', 'Medium', 'undead', 'Ghost Knight'),
		('ghostwalk-spider', '9', 'Large', 'monstrosity', 'Ghostwalk Spider'),
		('ghoul', '1', 'Medium', 'undead', 'Ghoul'),
		('ghoul-darakhul', '3', 'Medium', 'undead', 'Ghoul, Darakhul'),
		('ghoul-imperial', '4', 'Medium', 'undead', 'Ghoul, Imperial'),
		('ghoul-iron', '5', 'Medium', 'undead', 'Ghoul, Iron'),
		('ghoulsteed', '3', 'Large', 'undead', 'Ghoulsteed'),
		('giant-albino-bat', '3', 'Huge', 'monstrosity', 'Giant Albino Bat'),
		('giant-ant', '2', 'Large', 'beast', 'Giant Ant'),
		('giant-ant-queen', '4', 'Large', 'beast', 'Giant Ant Queen'),
		('giant-ape', '7', 'Huge', 'beast', 'Giant Ape'),
		('giant-badger', '1/4', 'Medium', 'beast', 'Giant Badger'),
		('giant-bat', '1/4', 'Large', 'beast', 'Giant Bat'),
		('giant-boar', '2', 'Large', 'beast', 'Giant Boar'),
		('giant-centipede', '1/4', 'Small', 'beast', 'Giant Centipede'),
		('giant-constrictor-snake', '2', 'Huge', 'beast', 'Giant Constrictor Snake'),
		('giant-crab', '1/8', 'Medium', 'beast', 'Giant Crab'),
		('giant-crocodile', '5', 'Huge', 'beast', 'Giant Crocodile'),
		('giant-eagle', '1', 'Large', 'beast', 'Giant Eagle'),
		('giant-elk', '2', 'Huge', 'beast', 'Giant Elk'),
		('giant-fire-beetle', '0', 'Small', 'beast', 'Giant Fire Beetle'),
		('giant-frog', '1/4', 'Medium', 'beast', 'Giant Frog'),
		('giant-goat', '1/2', 'Large', 'beast', 'Giant Goat'),
		('giant-hyena', '1', 'Large', 'beast', 'Giant Hyena'),
		('giant-lizard', '1/4', 'Large', 'beast', 'Giant Lizard'),
		('giant-moth', '1/8', 'Small', 'beast', 'Giant Moth'),
		('giant-octopus', '1', 'Large', 'beast', 'Giant Octopus'),
		('giant-owl', '1/4', 'Large', 'beast', 'Giant Owl'),
		('giant-poisonous-snake', '1/4', 'Medium', 'beast', 'Giant Poisonous Snake'),
		('giant-rat', '1/8', 'Small', 'beast', 'Giant Rat'),
		('giant-rat-diseased', '1/8', 'Small', 'beast', 'Giant Rat (Diseased)'),
		('giant-scorpion', '3', 'Large', 'beast', 'Giant Scorpion'),
		('giant-sea-horse', '1/2', 'Large', 'beast', 'Giant Sea Horse'),
		('giant-shark', '5', 'Huge', 'beast', 'Giant Shark'),
		('giant-shark-bowl', '8', 'Huge', 'ooze', 'Giant Shark Bowl'),
		('giant-sloth', '7', 'Large', 'beast', 'Giant Sloth'),
		('giant-spider', '1', 'Large', 'beast', 'Giant Spider'),
		('giant-toad', '1', 'Large', 'beast', 'Giant Toad'),
		('giant-vampire-bat', '2', 'Large', 'beast', 'Giant Vampire Bat'),
		('giant-vulture', '1', 'Large', 'beast', 'Giant Vulture'),
		('giant-wasp', '1/2', 'Medium', 'beast', 'Giant Wasp'),
		('giant-weasel', '1/8', 'Medium', 'beast', 'Giant Weasel'),
		('giant-wolf-spider', '1/4', 'Medium', 'beast', 'Giant Wolf Spider'),
		('gibbering-mouther', '2', 'Medium', 'aberration', 'Gibbering Mouther'),
		('gilded-devil', '7', 'Medium', 'fiend', 'Gilded Devil'),
		('glabrezu', '9', 'Large', 'fiend', 'Glabrezu'),
		('gladiator', '5', 'Medium', 'humanoid', 'Gladiator'),
		('glass-gator', '1', 'Large', 'beast', 'Glass Gator'),
		('glass-golem', '2', 'Small', 'construct', 'Glass Golem'),
		('gloomflower', '3', 'Tiny', 'plant', 'Gloomflower'),
		('gnarljak', '6', 'Small', 'construct', 'Gnarljak'),
		('gnoll', '1/2', 'Medium', 'humanoid', 'Gnoll'),
		('gnoll-havoc-runner', '3', 'Medium', 'humanoid', 'Gnoll Havoc Runner'),
		('gnoll-slaver', '3', 'Medium', 'humanoid', 'Gnoll Slaver'),
		('goat', '0', 'Medium', 'beast', 'Goat'),
		('goat-man', '3', 'Medium', 'monstrosity', 'Goat-Man'),
		('goblin', '1/4', 'Small', 'humanoid', 'Goblin'),
		('gold-dragon-wyrmling', '3', 'Medium', 'dragon', 'Gold Dragon Wyrmling'),
		('goliath-longlegs', '7', 'Gargantuan', 'monstrosity', 'Goliath Longlegs'),
		('goreling', '1/4', 'Small', 'undead', 'Goreling'),
		('gorgon', '5', 'Large', 'monstrosity', 'Gorgon'),
		('grave-behemoth', '10', 'Huge', 'undead', 'Grave Behemoth'),
		('gray-ooze', '1/2', 'Medium', 'ooze', 'Gray Ooze'),
		('gray-thirster', '2', 'Medium', 'undead', 'Gray Thirster'),
		('great-mandrake', '1', 'Tiny', 'plant', 'Great Mandrake'),
		('greater-death-butterfly-swarm', '6', 'Huge', 'swarm of tiny beasts', 'Greater Death Butterfly Swarm'),
		('greater-rakshasa', '15', 'Medium', 'fiend', 'Greater Rakshasa'),
		('greater-scrag', '7', 'Large', 'monstrosity', 'Greater Scrag'),
		('green-abyss-orc', '1/2', 'Medium', 'humanoid', 'Green Abyss Orc'),
		('green-dragon-wyrmling', '2', 'Medium', 'dragon', 'Green Dragon Wyrmling'),
		('green-hag', '3', 'Medium', 'fey', 'Green Hag'),
		('green-knight-of-the-woods', '6', 'Medium', 'fey', 'Green Knight of the Woods'),
		('grick', '2', 'Medium', 'monstrosity', 'Grick'),
		('griffon', '2', 'Large', 'monstrosity', 'Griffon'),
		('grim-jester', '11', 'Medium', 'undead', 'Grim Jester'),
		('grimlock', '1/4', 'Medium', 'humanoid', 'Grimlock'),
		('grindylow', '1', 'Medium', 'aberration', 'Grindylow'),
		('guard', '1/8', 'Medium', 'humanoid', 'Guard'),
		('guardian-naga', '10', 'Large', 'monstrosity', 'Guardian Naga'),
		('gug', '12', 'Huge', 'giant', 'Gug'),
		('gugalanna', '21', 'Huge', 'celestial', 'Gugalanna'),
		('gulon', '6', 'Large', 'monstrosity', 'Gulon'),
		('gumienniki', '1', 'Small', 'fiend', 'Gumienniki'),
		('gynosphinx', '11', 'Large', 'monstrosity', 'Gynosphinx'),
		('gypsosphinx', '14', 'Large', 'monstrosity', 'Gypsosphinx'),
		('hair-golem', '1/4', 'Small', 'construct', 'Hair Golem'),
		('half-red-dragon-veteran', '5', 'Medium', 'humanoid', 'Half-Red Dragon Veteran'),
		('hallowed-reed', '1/2', 'Medium', 'celestial', 'Hallowed Reed'),
		('harpy', '1', 'Medium', 'monstrosity', 'Harpy'),
		('haugbui', '13', 'Medium', 'undead', 'Haugbui'),
		('haunted-giant', '6', 'Huge', 'giant', 'Haunted Giant'),
		('hawk', '0', 'Tiny', 'beast', 'Hawk'),
		('heavy-cavalry', '2', 'Medium', 'humanoid', 'Heavy Cavalry'),
		('hell-hound', '3', 'Medium', 'fiend', 'Hell Hound'),
		('herald-of-blood', '12', 'Huge', 'fiend', 'Herald Of Blood'),
		('herald-of-darkness', '7', 'Large', 'fiend', 'Herald Of Darkness'),
		('hezrou', '8', 'Large', 'fiend', 'Hezrou'),
		('hierophant-lich', '9', 'Medium', 'undead', 'Hierophant Lich'),
		('hill-giant', '5', 'Huge', 'giant', 'Hill Giant'),
		('hippogriff', '1', 'Large', 'monstrosity', 'Hippogriff'),
		('hoard-golem', '12', 'Huge', 'construct', 'Hoard Golem');