
/**
 * All the action types for the root reducer
 */
export const ADD_ALL_MONSTERS = "ADD_ALL_MONSTERS";
export const ADD_USER = "ADD_USER";
export const REMOVE_USER = "REMOVE_USER";
export const CHANGE_ENCOUNTER = "CHANGE_ENCOUNTER";
export const ADD_ENCOUNTER = "ADD_ENCOUNTER";
export const ADD_TO_CURR = "ADD_TO_CURRENT_ENCOUNTER";
export const REMOVE_FROM_ENCOUNTER = "REMOVE_FROM_ENCOUNTER";
export const ADD_ID_TO_ENCOUNTER = "ADD_ID_TO_ENCOUNTER";
export const ADD_ALL_ENCOUNTERS = "ADD_ALL_ENCOUNTERS";
export const CHANGE_CURR_ENCOUNTER = "CHANGE_CURR_ENCOUNTER";
export const CHANGE_NUMBER_PLAYERS ="CHANGE_NUMBER_PLAYERS";